/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/auth/forgot-password": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Request a password reset email */
    post: operations["forgot-password"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/auth/login": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Log in with email and password */
    post: operations["login"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/auth/logout": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Log out */
    post: operations["logout"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/auth/register": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Register with email and password */
    post: operations["register"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/auth/reset-password": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Reset password with a token */
    post: operations["reset-password"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/auth/verify-email": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Verify email address with a token */
    post: operations["verify-email"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/cards/autocomplete": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Card name autocomplete
     * @description Typo-tolerant name search. Oracle-level: one entry per card with a representative printing.
     */
    get: operations["autocompleteCards"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/cards/search": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Search cards with filters */
    get: operations["searchCards"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/cards/{oracleId}/printings": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** All printings of an oracle card, newest first */
    get: operations["cardPrintings"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/collection": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** The session user's collection */
    get: operations["getCollection"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/collection/cards/{scryfallId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** Set the owned quantity of a printing (0 deletes) */
    put: operations["setCollectionQuantity"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/collection/cards/{scryfallId}/change-printing": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Re-key an owned printing to another printing of the same card */
    post: operations["changeCollectionPrinting"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/collection/import": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Add quantities onto the collection (bulk import commit) */
    post: operations["importCollectionItems"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/collection/import/resolve": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Resolve a pasted card list (pure read, nothing is written) */
    post: operations["resolveCollectionImport"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/cubes": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Browse public cubes */
    get: operations["listCubes"];
    put?: never;
    /** Create a cube */
    post: operations["createCube"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/cubes/{cubeId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Cube metadata */
    get: operations["getCube"];
    put?: never;
    post?: never;
    /** Delete a cube */
    delete: operations["deleteCube"];
    options?: never;
    head?: never;
    /** Update cube metadata */
    patch: operations["updateCube"];
    trace?: never;
  };
  "/api/cubes/{cubeId}/cards": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Cube card list, current or at a historical version */
    get: operations["getCubeCards"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/cubes/{cubeId}/changes": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Changelog, newest first */
    get: operations["listCubeChanges"];
    put?: never;
    /** Commit a batched diff as one changelog entry */
    post: operations["commitCubeChange"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/cubes/{cubeId}/wantlist": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Cards in the cube missing from the caller's collection */
    get: operations["getCubeWantlist"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/events": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** All visible events (admins also see drafts) */
    get: operations["listEvents"];
    put?: never;
    /** Create a draft event (organizer) */
    post: operations["createEvent"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/events/{eventId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Event detail with cubes, attendees, and the caller's registration */
    get: operations["getEvent"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Edit an event (field whitelist depends on lifecycle) */
    patch: operations["updateEvent"];
    trace?: never;
  };
  "/api/events/{eventId}/cancel": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Lifecycle: cancel */
    post: operations["cancelEvent"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/events/{eventId}/cubes": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** Replace the event's linked cubes (draft only) */
    put: operations["setEventCubes"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/events/{eventId}/finish": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Lifecycle: finish */
    post: operations["finishEvent"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/events/{eventId}/publish": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Lifecycle: publish */
    post: operations["publishEvent"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/events/{eventId}/register": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Register (or join the waitlist when full) */
    post: operations["registerForEvent"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/events/{eventId}/registration": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Cancel own registration (refund policy applies) */
    delete: operations["cancelMyRegistration"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/events/{eventId}/registration/pay": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Get a Stripe Checkout URL for the pending registration */
    post: operations["payRegistration"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/events/{eventId}/registrations": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Every registration incl. waitlist order and refund queue (organizer) */
    get: operations["listEventRegistrations"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/events/{eventId}/registrations/{registrationId}/deny-refund": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Deny a queued refund request (organizer) */
    post: operations["denyRefund"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/events/{eventId}/registrations/{registrationId}/refund": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Refund a queued or paid registration (organizer) */
    post: operations["refundRegistration"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/events/{eventId}/start": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Lifecycle: start */
    post: operations["startEvent"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/events/{eventId}/tournament": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Tournament aggregate: players, rounds, matches, standings */
    get: operations["getTournament"];
    /** Create the tournament (snapshot paid roster) or set planned rounds (organizer) */
    put: operations["upsertTournament"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/events/{eventId}/tournament/matches/{matchId}/result": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** Report or override a Bo3 result (player in the match, or organizer) */
    put: operations["reportMatchResult"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/events/{eventId}/tournament/players/{playerId}/drop": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Player drop (self or organizer) */
    post: operations["dropTournamentPlayer"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/events/{eventId}/tournament/players/{playerId}/undrop": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Player undrop (self or organizer) */
    post: operations["undropTournamentPlayer"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/events/{eventId}/tournament/rounds": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Pair the next round as a draft (organizer; creates the tournament if absent) */
    post: operations["pairNextRound"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/events/{eventId}/tournament/rounds/{number}/complete": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Complete the round (all results in) (organizer) */
    post: operations["completeRound"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/events/{eventId}/tournament/rounds/{number}/publish": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Publish the draft round (organizer) */
    post: operations["publishRound"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/events/{eventId}/tournament/rounds/{number}/reroll": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Regenerate the draft round's pairings (organizer) */
    post: operations["rerollRound"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/events/{eventId}/tournament/rounds/{number}/swap": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Swap two player slots in the draft round (organizer) */
    post: operations["swapRoundSlots"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/healthz": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Health check */
    get: operations["healthz"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/me": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Current user */
    get: operations["me"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/me/cubes": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List own cubes (both visibilities) */
    get: operations["listMyCubes"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    AutocompleteCardsOutputBody: {
      /**
       * Format: uri
       * @description A URL to the JSON Schema for this object.
       * @example https://example.com/schemas/AutocompleteCardsOutputBody.json
       */
      readonly $schema?: string;
      cards: components["schemas"]["CardSummary"][] | null;
    };
    CardDetail: {
      backImageNormal: string | null;
      /** Format: double */
      cmc: number;
      collectorNumber: string;
      colorIdentity: string[] | null;
      colors: string[] | null;
      imageNormal: string | null;
      imageSmall: string | null;
      manaCost: string;
      name: string;
      oracleId: string;
      oracleText: string;
      promo: boolean;
      rarity: string;
      /** @description YYYY-MM-DD */
      releasedAt: string;
      scryfallId: string;
      setCode: string;
      setName: string;
      typeLine: string;
    };
    CardPrintingsOutputBody: {
      /**
       * Format: uri
       * @description A URL to the JSON Schema for this object.
       * @example https://example.com/schemas/CardPrintingsOutputBody.json
       */
      readonly $schema?: string;
      printings: components["schemas"]["CardDetail"][] | null;
    };
    CardSummary: {
      imageSmall: string | null;
      manaCost: string;
      name: string;
      oracleId: string;
      /** @description Representative printing */
      scryfallId: string;
      typeLine: string;
    };
    ChangePrintingInputBody: {
      /**
       * Format: uri
       * @description A URL to the JSON Schema for this object.
       * @example https://example.com/schemas/ChangePrintingInputBody.json
       */
      readonly $schema?: string;
      newScryfallId: string;
    };
    ChangelogEntry: {
      adds: components["schemas"]["ChangelogItem"][] | null;
      authorName: string;
      /** Format: date-time */
      createdAt: string;
      id: string;
      note: string;
      removes: components["schemas"]["ChangelogItem"][] | null;
      /** Format: int32 */
      version: number;
    };
    ChangelogItem: {
      name: string;
      oracleId: string;
      /** Format: int32 */
      quantity: number;
    };
    CollectionItemEntry: {
      collectorNumber: string;
      imageNormal: string | null;
      imageSmall: string | null;
      manaCost: string;
      name: string;
      oracleId: string;
      /** Format: int32 */
      quantity: number;
      scryfallId: string;
      setCode: string;
      setName: string;
      typeLine: string;
    };
    CollectionItemOutputBody: {
      /**
       * Format: uri
       * @description A URL to the JSON Schema for this object.
       * @example https://example.com/schemas/CollectionItemOutputBody.json
       */
      readonly $schema?: string;
      /** @description absent after a quantity-0 delete */
      item?: components["schemas"]["CollectionItemEntry"];
    };
    CommitCubeChangeInputBody: {
      /**
       * Format: uri
       * @description A URL to the JSON Schema for this object.
       * @example https://example.com/schemas/CommitCubeChangeInputBody.json
       */
      readonly $schema?: string;
      adds?: components["schemas"]["CubeChangeAdd"][] | null;
      /** Format: int32 */
      expectedVersion: number;
      note?: string;
      removes?: components["schemas"]["CubeChangeRemove"][] | null;
    };
    CommitCubeChangeOutputBody: {
      /**
       * Format: uri
       * @description A URL to the JSON Schema for this object.
       * @example https://example.com/schemas/CommitCubeChangeOutputBody.json
       */
      readonly $schema?: string;
      change: components["schemas"]["ChangelogEntry"];
      /** Format: int32 */
      version: number;
    };
    CreateCubeInputBody: {
      /**
       * Format: uri
       * @description A URL to the JSON Schema for this object.
       * @example https://example.com/schemas/CreateCubeInputBody.json
       */
      readonly $schema?: string;
      description?: string;
      name: string;
      /** @enum {string} */
      visibility: "public" | "private";
    };
    CreateEventInputBody: {
      /**
       * Format: uri
       * @description A URL to the JSON Schema for this object.
       * @example https://example.com/schemas/CreateEventInputBody.json
       */
      readonly $schema?: string;
      currency?: string;
      description?: string;
      /** Format: int32 */
      feeCents: number;
      location?: string;
      /** Format: int32 */
      maxParticipants: number;
      name: string;
      /** Format: date-time */
      refundDeadline?: string;
      /** Format: date-time */
      startsAt: string;
    };
    CubeCardEntry: {
      /** Format: double */
      cmc: number;
      colorIdentity: string[] | null;
      colors: string[] | null;
      imageNormal: string | null;
      imageSmall: string | null;
      manaCost: string;
      name: string;
      oracleId: string;
      /** Format: int32 */
      quantity: number;
      rarity: string;
      scryfallId: string;
      typeLine: string;
    };
    CubeChangeAdd: {
      /** Format: int32 */
      quantity: number;
      scryfallId: string;
    };
    CubeChangeRemove: {
      oracleId: string;
      /** Format: int32 */
      quantity: number;
    };
    CubeDetail: {
      /**
       * Format: uri
       * @description A URL to the JSON Schema for this object.
       * @example https://example.com/schemas/CubeDetail.json
       */
      readonly $schema?: string;
      /** Format: int64 */
      cardCount: number;
      /** Format: date-time */
      createdAt: string;
      description: string;
      id: string;
      name: string;
      ownerId: string;
      ownerName: string;
      /** Format: date-time */
      updatedAt: string;
      /**
       * Format: int32
       * @description Optimistic-concurrency token for commits
       */
      version: number;
      /** @enum {string} */
      visibility: "public" | "private";
    };
    CubeSummary: {
      /**
       * Format: int64
       * @description Sum of quantities
       */
      cardCount: number;
      description: string;
      id: string;
      name: string;
      ownerName: string;
      /** Format: date-time */
      updatedAt: string;
      /** @enum {string} */
      visibility: "public" | "private";
    };
    ErrorDetail: {
      /** @description Where the error occurred, e.g. 'body.items[3].tags' or 'path.thing-id' */
      location?: string;
      /** @description Error message text */
      message?: string;
      /** @description The value at the given location */
      value?: unknown;
    };
    ErrorModel: {
      /**
       * Format: uri
       * @description A URL to the JSON Schema for this object.
       * @example https://example.com/schemas/ErrorModel.json
       */
      readonly $schema?: string;
      /**
       * @description A human-readable explanation specific to this occurrence of the problem.
       * @example Property foo is required but is missing.
       */
      detail?: string;
      /** @description Optional list of individual error details */
      errors?: components["schemas"]["ErrorDetail"][] | null;
      /**
       * Format: uri
       * @description A URI reference that identifies the specific occurrence of the problem.
       * @example https://example.com/error-log/abc123
       */
      instance?: string;
      /**
       * Format: int64
       * @description HTTP status code
       * @example 400
       */
      status?: number;
      /**
       * @description A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
       * @example Bad Request
       */
      title?: string;
      /**
       * Format: uri
       * @description A URI reference to human-readable documentation for the error.
       * @default about:blank
       * @example https://example.com/errors/example
       */
      type: string;
    };
    EventCubeEntry: {
      cubeChangeId?: string;
      cubeId: string;
      cubeName: string;
      /** Format: date-time */
      pinnedAt?: string;
      /** Format: int32 */
      pinnedVersion?: number;
    };
    EventCubeLink: {
      cubeChangeId?: string;
      cubeId: string;
    };
    EventDetailBody: {
      /**
       * Format: uri
       * @description A URL to the JSON Schema for this object.
       * @example https://example.com/schemas/EventDetailBody.json
       */
      readonly $schema?: string;
      attendees: string[] | null;
      cubes: components["schemas"]["EventCubeEntry"][] | null;
      currency: string;
      description: string;
      /** Format: int32 */
      feeCents: number;
      id: string;
      location: string;
      /** Format: int32 */
      maxParticipants: number;
      myRegistration?: components["schemas"]["RegistrationInfo"];
      myRegistrationStatus?: string;
      name: string;
      organizerName: string;
      /** Format: int32 */
      paidCount: number;
      /** Format: int32 */
      pendingCount: number;
      /** Format: date-time */
      refundDeadline?: string;
      /** Format: date-time */
      startsAt: string;
      /** @enum {string} */
      status: "draft" | "published" | "started" | "finished" | "cancelled";
      /** Format: int32 */
      waitlistCount: number;
    };
    EventRegistrationRow: {
      /** Format: date-time */
      createdAt: string;
      displayName: string;
      email: string;
      /** Format: date-time */
      expiresAt?: string;
      id: string;
      /** Format: date-time */
      paidAt?: string;
      /** @enum {string} */
      status:
        | "pending_payment"
        | "paid"
        | "waitlisted"
        | "cancelled"
        | "refund_requested"
        | "refunded"
        | "expired";
      /** Format: int64 */
      waitlistPos?: number;
    };
    EventSummary: {
      currency: string;
      /** Format: int32 */
      feeCents: number;
      id: string;
      location: string;
      /** Format: int32 */
      maxParticipants: number;
      myRegistrationStatus?: string;
      name: string;
      /** Format: int32 */
      paidCount: number;
      /** Format: int32 */
      pendingCount: number;
      /** Format: date-time */
      startsAt: string;
      /** @enum {string} */
      status: "draft" | "published" | "started" | "finished" | "cancelled";
      /** Format: int32 */
      waitlistCount: number;
    };
    ForgotPasswordInputBody: {
      /**
       * Format: uri
       * @description A URL to the JSON Schema for this object.
       * @example https://example.com/schemas/ForgotPasswordInputBody.json
       */
      readonly $schema?: string;
      /** Format: email */
      email: string;
    };
    GetCollectionOutputBody: {
      /**
       * Format: uri
       * @description A URL to the JSON Schema for this object.
       * @example https://example.com/schemas/GetCollectionOutputBody.json
       */
      readonly $schema?: string;
      items: components["schemas"]["CollectionItemEntry"][] | null;
      /**
       * Format: int64
       * @description Distinct printings matching the filter
       */
      total: number;
      /**
       * Format: int64
       * @description Sum of their quantities
       */
      totalCopies: number;
    };
    GetCubeCardsOutputBody: {
      /**
       * Format: uri
       * @description A URL to the JSON Schema for this object.
       * @example https://example.com/schemas/GetCubeCardsOutputBody.json
       */
      readonly $schema?: string;
      cards: components["schemas"]["CubeCardEntry"][] | null;
      /** Format: int32 */
      version: number;
    };
    GetWantlistOutputBody: {
      /**
       * Format: uri
       * @description A URL to the JSON Schema for this object.
       * @example https://example.com/schemas/GetWantlistOutputBody.json
       */
      readonly $schema?: string;
      cubeName: string;
      items: components["schemas"]["WantlistEntry"][] | null;
      /** Format: int64 */
      totalMissing: number;
    };
    HealthOutputBody: {
      /**
       * Format: uri
       * @description A URL to the JSON Schema for this object.
       * @example https://example.com/schemas/HealthOutputBody.json
       */
      readonly $schema?: string;
      /** @example ok */
      status: string;
    };
    ImportCardMatch: {
      collectorNumber: string;
      imageNormal: string | null;
      imageSmall: string | null;
      manaCost: string;
      name: string;
      oracleId: string;
      scryfallId: string;
      setCode: string;
      setName: string;
      typeLine: string;
    };
    ImportItemsInputBody: {
      /**
       * Format: uri
       * @description A URL to the JSON Schema for this object.
       * @example https://example.com/schemas/ImportItemsInputBody.json
       */
      readonly $schema?: string;
      items: components["schemas"]["Item"][] | null;
    };
    ImportItemsOutputBody: {
      /**
       * Format: uri
       * @description A URL to the JSON Schema for this object.
       * @example https://example.com/schemas/ImportItemsOutputBody.json
       */
      readonly $schema?: string;
      /** Format: int32 */
      addedRows: number;
      /** Format: int32 */
      updatedRows: number;
    };
    ImportResolveLine: {
      /** Format: int32 */
      lineNumber: number;
      match?: components["schemas"]["ImportCardMatch"];
      /** Format: int32 */
      quantity: number;
      raw: string;
      /** @enum {string} */
      status: "matched" | "ambiguous" | "unmatched";
      suggestions?: components["schemas"]["ImportCardMatch"][] | null;
    };
    Item: {
      /** Format: int32 */
      quantity: number;
      scryfallId: string;
    };
    ListCubeChangesOutputBody: {
      /**
       * Format: uri
       * @description A URL to the JSON Schema for this object.
       * @example https://example.com/schemas/ListCubeChangesOutputBody.json
       */
      readonly $schema?: string;
      changes: components["schemas"]["ChangelogEntry"][] | null;
      /** Format: int64 */
      total: number;
    };
    ListCubesOutputBody: {
      /**
       * Format: uri
       * @description A URL to the JSON Schema for this object.
       * @example https://example.com/schemas/ListCubesOutputBody.json
       */
      readonly $schema?: string;
      cubes: components["schemas"]["CubeSummary"][] | null;
      /** Format: int64 */
      total: number;
    };
    ListEventsOutputBody: {
      /**
       * Format: uri
       * @description A URL to the JSON Schema for this object.
       * @example https://example.com/schemas/ListEventsOutputBody.json
       */
      readonly $schema?: string;
      events: components["schemas"]["EventSummary"][] | null;
    };
    ListRegistrationsOutputBody: {
      /**
       * Format: uri
       * @description A URL to the JSON Schema for this object.
       * @example https://example.com/schemas/ListRegistrationsOutputBody.json
       */
      readonly $schema?: string;
      registrations: components["schemas"]["EventRegistrationRow"][] | null;
    };
    LoginInputBody: {
      /**
       * Format: uri
       * @description A URL to the JSON Schema for this object.
       * @example https://example.com/schemas/LoginInputBody.json
       */
      readonly $schema?: string;
      /** Format: email */
      email: string;
      password: string;
    };
    PayOutputBody: {
      /**
       * Format: uri
       * @description A URL to the JSON Schema for this object.
       * @example https://example.com/schemas/PayOutputBody.json
       */
      readonly $schema?: string;
      checkoutUrl: string;
    };
    RegisterInputBody: {
      /**
       * Format: uri
       * @description A URL to the JSON Schema for this object.
       * @example https://example.com/schemas/RegisterInputBody.json
       */
      readonly $schema?: string;
      displayName: string;
      /** Format: email */
      email: string;
      password: string;
    };
    RegistrationInfo: {
      /**
       * Format: uri
       * @description A URL to the JSON Schema for this object.
       * @example https://example.com/schemas/RegistrationInfo.json
       */
      readonly $schema?: string;
      /** Format: date-time */
      expiresAt?: string;
      id: string;
      /** Format: date-time */
      paidAt?: string;
      /** @enum {string} */
      status:
        | "pending_payment"
        | "paid"
        | "waitlisted"
        | "cancelled"
        | "refund_requested"
        | "refunded"
        | "expired";
      /** Format: int64 */
      waitlistPos?: number;
    };
    ReportResultInputBody: {
      /**
       * Format: uri
       * @description A URL to the JSON Schema for this object.
       * @example https://example.com/schemas/ReportResultInputBody.json
       */
      readonly $schema?: string;
      /** Format: int32 */
      draws: number;
      /** Format: int32 */
      p1Games: number;
      /** Format: int32 */
      p2Games: number;
    };
    ResetPasswordInputBody: {
      /**
       * Format: uri
       * @description A URL to the JSON Schema for this object.
       * @example https://example.com/schemas/ResetPasswordInputBody.json
       */
      readonly $schema?: string;
      newPassword: string;
      token: string;
    };
    ResolveImportInputBody: {
      /**
       * Format: uri
       * @description A URL to the JSON Schema for this object.
       * @example https://example.com/schemas/ResolveImportInputBody.json
       */
      readonly $schema?: string;
      text: string;
    };
    ResolveImportOutputBody: {
      /**
       * Format: uri
       * @description A URL to the JSON Schema for this object.
       * @example https://example.com/schemas/ResolveImportOutputBody.json
       */
      readonly $schema?: string;
      lines: components["schemas"]["ImportResolveLine"][] | null;
    };
    SearchCardsOutputBody: {
      /**
       * Format: uri
       * @description A URL to the JSON Schema for this object.
       * @example https://example.com/schemas/SearchCardsOutputBody.json
       */
      readonly $schema?: string;
      cards: components["schemas"]["CardDetail"][] | null;
      /** Format: int64 */
      total: number;
    };
    SetCollectionQuantityInputBody: {
      /**
       * Format: uri
       * @description A URL to the JSON Schema for this object.
       * @example https://example.com/schemas/SetCollectionQuantityInputBody.json
       */
      readonly $schema?: string;
      /**
       * Format: int32
       * @description 0 deletes the row
       */
      quantity: number;
    };
    SetEventCubesInputBody: {
      /**
       * Format: uri
       * @description A URL to the JSON Schema for this object.
       * @example https://example.com/schemas/SetEventCubesInputBody.json
       */
      readonly $schema?: string;
      cubes: components["schemas"]["EventCubeLink"][] | null;
    };
    SwapInputBody: {
      /**
       * Format: uri
       * @description A URL to the JSON Schema for this object.
       * @example https://example.com/schemas/SwapInputBody.json
       */
      readonly $schema?: string;
      a: components["schemas"]["SwapSlot"];
      b: components["schemas"]["SwapSlot"];
    };
    SwapSlot: {
      matchId: string;
      /** Format: int32 */
      slot: number;
    };
    TournamentInfo: {
      /**
       * Format: uri
       * @description A URL to the JSON Schema for this object.
       * @example https://example.com/schemas/TournamentInfo.json
       */
      readonly $schema?: string;
      /** Format: int32 */
      currentRound?: number;
      eventId: string;
      /** Format: int32 */
      plannedRounds: number;
      players: components["schemas"]["TournamentPlayerInfo"][] | null;
      rounds: components["schemas"]["TournamentRoundInfo"][] | null;
      standings: components["schemas"]["TournamentStandingInfo"][] | null;
    };
    TournamentMatchInfo: {
      /** Format: int32 */
      draws?: number;
      id: string;
      /** Format: int32 */
      p1Games?: number;
      /** Format: int32 */
      p2Games?: number;
      player1Id: string;
      player2Id?: string;
      /** Format: date-time */
      reportedAt?: string;
      /** Format: int32 */
      tableNumber: number;
    };
    TournamentPlayerInfo: {
      displayName: string;
      dropped: boolean;
      id: string;
      userId: string;
    };
    TournamentRoundInfo: {
      matches: components["schemas"]["TournamentMatchInfo"][] | null;
      /** Format: int32 */
      number: number;
      /** @enum {string} */
      status: "draft" | "published" | "completed";
    };
    TournamentStandingInfo: {
      displayName: string;
      dropped: boolean;
      /** Format: double */
      gwPercent: number;
      /** Format: int64 */
      matchPoints: number;
      /** Format: double */
      ogwPercent: number;
      /** Format: double */
      omwPercent: number;
      playerId: string;
      /** Format: int64 */
      rank: number;
    };
    UpdateCubeInputBody: {
      /**
       * Format: uri
       * @description A URL to the JSON Schema for this object.
       * @example https://example.com/schemas/UpdateCubeInputBody.json
       */
      readonly $schema?: string;
      description?: string;
      name?: string;
      /** @enum {string} */
      visibility?: "public" | "private";
    };
    UpdateEventInputBody: {
      /**
       * Format: uri
       * @description A URL to the JSON Schema for this object.
       * @example https://example.com/schemas/UpdateEventInputBody.json
       */
      readonly $schema?: string;
      currency?: string;
      description?: string;
      /** Format: int32 */
      feeCents?: number;
      location?: string;
      /** Format: int32 */
      maxParticipants?: number;
      name?: string;
      /** Format: date-time */
      refundDeadline?: string;
      /** Format: date-time */
      startsAt?: string;
    };
    UpsertTournamentInputBody: {
      /**
       * Format: uri
       * @description A URL to the JSON Schema for this object.
       * @example https://example.com/schemas/UpsertTournamentInputBody.json
       */
      readonly $schema?: string;
      /** Format: int32 */
      plannedRounds?: number;
    };
    UserBody: {
      /**
       * Format: uri
       * @description A URL to the JSON Schema for this object.
       * @example https://example.com/schemas/UserBody.json
       */
      readonly $schema?: string;
      displayName: string;
      email: string;
      id: string;
      providers: string[] | null;
      /** @enum {string} */
      role: "user" | "admin";
    };
    VerifyEmailInputBody: {
      /**
       * Format: uri
       * @description A URL to the JSON Schema for this object.
       * @example https://example.com/schemas/VerifyEmailInputBody.json
       */
      readonly $schema?: string;
      token: string;
    };
    WantlistEntry: {
      /** Format: int32 */
      cubeQuantity: number;
      imageNormal: string | null;
      imageSmall: string | null;
      manaCost: string;
      /** Format: int32 */
      missingQuantity: number;
      name: string;
      oracleId: string;
      /** Format: int32 */
      ownedQuantity: number;
      /** @description The cube's chosen printing */
      scryfallId: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  "forgot-password": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ForgotPasswordInputBody"];
      };
    };
    responses: {
      /** @description No Content */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["ErrorModel"];
        };
      };
    };
  };
  login: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["LoginInputBody"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          "Set-Cookie"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UserBody"];
        };
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["ErrorModel"];
        };
      };
    };
  };
  logout: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: {
        cp_session?: string;
      };
    };
    requestBody?: never;
    responses: {
      /** @description No Content */
      204: {
        headers: {
          "Set-Cookie"?: string;
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["ErrorModel"];
        };
      };
    };
  };
  register: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RegisterInputBody"];
      };
    };
    responses: {
      /** @description No Content */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["ErrorModel"];
        };
      };
    };
  };
  "reset-password": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ResetPasswordInputBody"];
      };
    };
    responses: {
      /** @description No Content */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["ErrorModel"];
        };
      };
    };
  };
  "verify-email": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["VerifyEmailInputBody"];
      };
    };
    responses: {
      /** @description No Content */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["ErrorModel"];
        };
      };
    };
  };
  autocompleteCards: {
    parameters: {
      query: {
        /** @description Card name, fuzzy */
        q: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AutocompleteCardsOutputBody"];
        };
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["ErrorModel"];
        };
      };
    };
  };
  searchCards: {
    parameters: {
      query?: {
        /** @description Fuzzy name filter */
        name?: string;
        /** @description Color identity ⊆ selection; C = include colorless-only */
        colors?: ("W" | "U" | "B" | "R" | "G" | "C")[] | null;
        /** @description Type line substring */
        type?: string;
        /** @description Lower CMC bound (0 = none) */
        cmcMin?: number;
        /** @description Upper CMC bound (-1 = none) */
        cmcMax?: number;
        rarity?: "common" | "uncommon" | "rare" | "mythic" | "special" | "bonus";
        /** @description Set code */
        set?: string;
        limit?: number;
        offset?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SearchCardsOutputBody"];
        };
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["ErrorModel"];
        };
      };
    };
  };
  cardPrintings: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        oracleId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CardPrintingsOutputBody"];
        };
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["ErrorModel"];
        };
      };
    };
  };
  getCollection: {
    parameters: {
      query?: {
        /** @description Name filter (substring, case-insensitive) */
        search?: string;
        limit?: number;
        offset?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GetCollectionOutputBody"];
        };
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["ErrorModel"];
        };
      };
    };
  };
  setCollectionQuantity: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        scryfallId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SetCollectionQuantityInputBody"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CollectionItemOutputBody"];
        };
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["ErrorModel"];
        };
      };
    };
  };
  changeCollectionPrinting: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        scryfallId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ChangePrintingInputBody"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CollectionItemOutputBody"];
        };
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["ErrorModel"];
        };
      };
    };
  };
  importCollectionItems: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ImportItemsInputBody"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ImportItemsOutputBody"];
        };
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["ErrorModel"];
        };
      };
    };
  };
  resolveCollectionImport: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ResolveImportInputBody"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ResolveImportOutputBody"];
        };
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["ErrorModel"];
        };
      };
    };
  };
  listCubes: {
    parameters: {
      query?: {
        /** @description Fuzzy name filter (min 2 chars to take effect) */
        q?: string;
        limit?: number;
        offset?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ListCubesOutputBody"];
        };
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["ErrorModel"];
        };
      };
    };
  };
  createCube: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateCubeInputBody"];
      };
    };
    responses: {
      /** @description Created */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CubeDetail"];
        };
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["ErrorModel"];
        };
      };
    };
  };
  getCube: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        cubeId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CubeDetail"];
        };
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["ErrorModel"];
        };
      };
    };
  };
  deleteCube: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        cubeId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description No Content */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["ErrorModel"];
        };
      };
    };
  };
  updateCube: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        cubeId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateCubeInputBody"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CubeDetail"];
        };
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["ErrorModel"];
        };
      };
    };
  };
  getCubeCards: {
    parameters: {
      query?: {
        /** @description -1 = current; otherwise a historical version to reconstruct */
        atVersion?: number;
      };
      header?: never;
      path: {
        cubeId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GetCubeCardsOutputBody"];
        };
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["ErrorModel"];
        };
      };
    };
  };
  listCubeChanges: {
    parameters: {
      query?: {
        limit?: number;
        offset?: number;
      };
      header?: never;
      path: {
        cubeId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ListCubeChangesOutputBody"];
        };
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["ErrorModel"];
        };
      };
    };
  };
  commitCubeChange: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        cubeId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CommitCubeChangeInputBody"];
      };
    };
    responses: {
      /** @description Created */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CommitCubeChangeOutputBody"];
        };
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["ErrorModel"];
        };
      };
    };
  };
  getCubeWantlist: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        cubeId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GetWantlistOutputBody"];
        };
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["ErrorModel"];
        };
      };
    };
  };
  listEvents: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ListEventsOutputBody"];
        };
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["ErrorModel"];
        };
      };
    };
  };
  createEvent: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateEventInputBody"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["EventDetailBody"];
        };
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["ErrorModel"];
        };
      };
    };
  };
  getEvent: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        eventId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["EventDetailBody"];
        };
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["ErrorModel"];
        };
      };
    };
  };
  updateEvent: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        eventId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateEventInputBody"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["EventDetailBody"];
        };
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["ErrorModel"];
        };
      };
    };
  };
  cancelEvent: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        eventId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["EventDetailBody"];
        };
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["ErrorModel"];
        };
      };
    };
  };
  setEventCubes: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        eventId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SetEventCubesInputBody"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["EventDetailBody"];
        };
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["ErrorModel"];
        };
      };
    };
  };
  finishEvent: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        eventId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["EventDetailBody"];
        };
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["ErrorModel"];
        };
      };
    };
  };
  publishEvent: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        eventId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["EventDetailBody"];
        };
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["ErrorModel"];
        };
      };
    };
  };
  registerForEvent: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        eventId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RegistrationInfo"];
        };
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["ErrorModel"];
        };
      };
    };
  };
  cancelMyRegistration: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        eventId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RegistrationInfo"];
        };
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["ErrorModel"];
        };
      };
    };
  };
  payRegistration: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        eventId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PayOutputBody"];
        };
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["ErrorModel"];
        };
      };
    };
  };
  listEventRegistrations: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        eventId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ListRegistrationsOutputBody"];
        };
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["ErrorModel"];
        };
      };
    };
  };
  denyRefund: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        eventId: string;
        registrationId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RegistrationInfo"];
        };
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["ErrorModel"];
        };
      };
    };
  };
  refundRegistration: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        eventId: string;
        registrationId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RegistrationInfo"];
        };
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["ErrorModel"];
        };
      };
    };
  };
  startEvent: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        eventId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["EventDetailBody"];
        };
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["ErrorModel"];
        };
      };
    };
  };
  getTournament: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        eventId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TournamentInfo"];
        };
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["ErrorModel"];
        };
      };
    };
  };
  upsertTournament: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        eventId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpsertTournamentInputBody"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TournamentInfo"];
        };
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["ErrorModel"];
        };
      };
    };
  };
  reportMatchResult: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        eventId: string;
        matchId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ReportResultInputBody"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TournamentInfo"];
        };
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["ErrorModel"];
        };
      };
    };
  };
  dropTournamentPlayer: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        eventId: string;
        playerId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TournamentInfo"];
        };
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["ErrorModel"];
        };
      };
    };
  };
  undropTournamentPlayer: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        eventId: string;
        playerId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TournamentInfo"];
        };
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["ErrorModel"];
        };
      };
    };
  };
  pairNextRound: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        eventId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TournamentInfo"];
        };
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["ErrorModel"];
        };
      };
    };
  };
  completeRound: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        eventId: string;
        number: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TournamentInfo"];
        };
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["ErrorModel"];
        };
      };
    };
  };
  publishRound: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        eventId: string;
        number: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TournamentInfo"];
        };
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["ErrorModel"];
        };
      };
    };
  };
  rerollRound: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        eventId: string;
        number: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TournamentInfo"];
        };
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["ErrorModel"];
        };
      };
    };
  };
  swapRoundSlots: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        eventId: string;
        number: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SwapInputBody"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TournamentInfo"];
        };
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["ErrorModel"];
        };
      };
    };
  };
  healthz: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HealthOutputBody"];
        };
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["ErrorModel"];
        };
      };
    };
  };
  me: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UserBody"];
        };
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["ErrorModel"];
        };
      };
    };
  };
  listMyCubes: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ListCubesOutputBody"];
        };
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["ErrorModel"];
        };
      };
    };
  };
}
