// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const consumeAuthToken = `-- name: ConsumeAuthToken :one
delete from auth_tokens
where token_hash = $1 and purpose = $2 and expires_at > now()
returning user_id
`

type ConsumeAuthTokenParams struct {
	TokenHash []byte
	Purpose   string
}

func (q *Queries) ConsumeAuthToken(ctx context.Context, arg ConsumeAuthTokenParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, consumeAuthToken, arg.TokenHash, arg.Purpose)
	var user_id uuid.UUID
	err := row.Scan(&user_id)
	return user_id, err
}

const createAuthToken = `-- name: CreateAuthToken :exec
insert into auth_tokens (token_hash, user_id, purpose, expires_at)
values ($1, $2, $3, $4)
`

type CreateAuthTokenParams struct {
	TokenHash []byte
	UserID    uuid.UUID
	Purpose   string
	ExpiresAt time.Time
}

func (q *Queries) CreateAuthToken(ctx context.Context, arg CreateAuthTokenParams) error {
	_, err := q.db.Exec(
		ctx, createAuthToken,
		arg.TokenHash,
		arg.UserID,
		arg.Purpose,
		arg.ExpiresAt,
	)
	return err
}

const createOAuthIdentity = `-- name: CreateOAuthIdentity :exec
insert into oauth_identities (provider, provider_user_id, user_id)
values ($1, $2, $3)
`

type CreateOAuthIdentityParams struct {
	Provider       string
	ProviderUserID string
	UserID         uuid.UUID
}

func (q *Queries) CreateOAuthIdentity(ctx context.Context, arg CreateOAuthIdentityParams) error {
	_, err := q.db.Exec(ctx, createOAuthIdentity, arg.Provider, arg.ProviderUserID, arg.UserID)
	return err
}

const createSession = `-- name: CreateSession :exec
insert into sessions (token_hash, user_id, expires_at)
values ($1, $2, $3)
`

type CreateSessionParams struct {
	TokenHash []byte
	UserID    uuid.UUID
	ExpiresAt time.Time
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.Exec(ctx, createSession, arg.TokenHash, arg.UserID, arg.ExpiresAt)
	return err
}

const createUser = `-- name: CreateUser :one
insert into users (email, display_name, password_hash, email_verified_at)
values (lower($1), $2, $3, $4)
returning id, email, display_name, password_hash, email_verified_at, created_at
`

type CreateUserParams struct {
	Email           string
	DisplayName     string
	PasswordHash    *string
	EmailVerifiedAt *time.Time
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(
		ctx, createUser,
		arg.Email,
		arg.DisplayName,
		arg.PasswordHash,
		arg.EmailVerifiedAt,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.PasswordHash,
		&i.EmailVerifiedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteSession = `-- name: DeleteSession :exec
delete from sessions where token_hash = $1
`

func (q *Queries) DeleteSession(ctx context.Context, tokenHash []byte) error {
	_, err := q.db.Exec(ctx, deleteSession, tokenHash)
	return err
}

const deleteSessionsForUser = `-- name: DeleteSessionsForUser :exec
delete from sessions where user_id = $1
`

func (q *Queries) DeleteSessionsForUser(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteSessionsForUser, userID)
	return err
}

const getOAuthIdentity = `-- name: GetOAuthIdentity :one
select provider, provider_user_id, user_id, created_at from oauth_identities where provider = $1 and provider_user_id = $2
`

type GetOAuthIdentityParams struct {
	Provider       string
	ProviderUserID string
}

func (q *Queries) GetOAuthIdentity(ctx context.Context, arg GetOAuthIdentityParams) (OauthIdentity, error) {
	row := q.db.QueryRow(ctx, getOAuthIdentity, arg.Provider, arg.ProviderUserID)
	var i OauthIdentity
	err := row.Scan(
		&i.Provider,
		&i.ProviderUserID,
		&i.UserID,
		&i.CreatedAt,
	)
	return i, err
}

const getSessionUserID = `-- name: GetSessionUserID :one
select user_id from sessions where token_hash = $1 and expires_at > now()
`

func (q *Queries) GetSessionUserID(ctx context.Context, tokenHash []byte) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getSessionUserID, tokenHash)
	var user_id uuid.UUID
	err := row.Scan(&user_id)
	return user_id, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
select id, email, display_name, password_hash, email_verified_at, created_at from users where email = lower($1)
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.PasswordHash,
		&i.EmailVerifiedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
select id, email, display_name, password_hash, email_verified_at, created_at from users where id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.PasswordHash,
		&i.EmailVerifiedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listProvidersForUser = `-- name: ListProvidersForUser :many
select provider from oauth_identities where user_id = $1 order by provider
`

func (q *Queries) ListProvidersForUser(ctx context.Context, userID uuid.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listProvidersForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var provider string
		if err := rows.Scan(&provider); err != nil {
			return nil, err
		}
		items = append(items, provider)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markEmailVerified = `-- name: MarkEmailVerified :exec
update users set email_verified_at = now() where id = $1 and email_verified_at is null
`

func (q *Queries) MarkEmailVerified(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markEmailVerified, id)
	return err
}

const setPasswordHash = `-- name: SetPasswordHash :exec
update users set password_hash = $1 where id = $2
`

type SetPasswordHashParams struct {
	PasswordHash *string
	ID           uuid.UUID
}

func (q *Queries) SetPasswordHash(ctx context.Context, arg SetPasswordHashParams) error {
	_, err := q.db.Exec(ctx, setPasswordHash, arg.PasswordHash, arg.ID)
	return err
}
