// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cards.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const autocompleteCards = `-- name: AutocompleteCards :many
with matches as (
    select distinct on (oracle_id) scryfall_id, oracle_id, name, normalized_name, released_at, set_code, set_name, collector_number, rarity, layout, mana_cost, cmc, type_line, oracle_text, colors, color_identity, promo, image_small, image_normal, back_image_small, back_image_normal, updated_at
    from cards
    where normalized_name like $1 || '%'
       or $2::text <% normalized_name
    order by oracle_id, promo, released_at desc, (image_small is null)
)
select scryfall_id, oracle_id, name, mana_cost, type_line, image_small
from matches
order by
    (normalized_name like $1 || '%') desc,
    word_similarity($2, normalized_name) desc,
    similarity($2, normalized_name) desc,
    name asc
limit 15
`

type AutocompleteCardsParams struct {
	Prefix *string
	Query  string
}

type AutocompleteCardsRow struct {
	ScryfallID uuid.UUID
	OracleID   uuid.UUID
	Name       string
	ManaCost   string
	TypeLine   string
	ImageSmall *string
}

// Autocomplete: oracle-level with a representative printing (non-promo
// first, then newest, then has-image). Prefix matches rank above fuzzy
// word-similarity matches. The CTE selects * because DISTINCT ON needs to
// order by promo/released_at, which are not in the output list.
// The <% operator (word-similarity commutator) is index-backed by the trgm
// GIN index on normalized_name; the threshold is set at the database level
// via pg_trgm.word_similarity_threshold (see migration 00003), not inlined
// here, because the function-call form defeats the index. ORDER BY still
// uses word_similarity()/similarity() for ranking — that's fine post-filter.
func (q *Queries) AutocompleteCards(ctx context.Context, arg AutocompleteCardsParams) ([]AutocompleteCardsRow, error) {
	rows, err := q.db.Query(ctx, autocompleteCards, arg.Prefix, arg.Query)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AutocompleteCardsRow
	for rows.Next() {
		var i AutocompleteCardsRow
		if err := rows.Scan(
			&i.ScryfallID,
			&i.OracleID,
			&i.Name,
			&i.ManaCost,
			&i.TypeLine,
			&i.ImageSmall,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countCards = `-- name: CountCards :one
select count(*) from cards
`

func (q *Queries) CountCards(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countCards)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSyncRun = `-- name: CreateSyncRun :one
insert into card_sync_runs (status) values ('running') returning id
`

func (q *Queries) CreateSyncRun(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, createSyncRun)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deleteCardsMissingFromStaging = `-- name: DeleteCardsMissingFromStaging :execrows
delete from cards
where scryfall_id not in (select scryfall_id from cards_staging)
`

func (q *Queries) DeleteCardsMissingFromStaging(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCardsMissingFromStaging)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const failStaleRunningSyncRuns = `-- name: FailStaleRunningSyncRuns :exec
update card_sync_runs
set status = 'failed', finished_at = now(), error = 'interrupted (process restart)'
where status = 'running'
`

func (q *Queries) FailStaleRunningSyncRuns(ctx context.Context) error {
	_, err := q.db.Exec(ctx, failStaleRunningSyncRuns)
	return err
}

const finishSyncRunFailure = `-- name: FinishSyncRunFailure :exec
update card_sync_runs
set status = 'failed', finished_at = now(), error = $1
where id = $2
`

type FinishSyncRunFailureParams struct {
	Error *string
	ID    int64
}

func (q *Queries) FinishSyncRunFailure(ctx context.Context, arg FinishSyncRunFailureParams) error {
	_, err := q.db.Exec(ctx, finishSyncRunFailure, arg.Error, arg.ID)
	return err
}

const finishSyncRunSuccess = `-- name: FinishSyncRunSuccess :exec
update card_sync_runs
set status = 'succeeded', finished_at = now(),
    bulk_updated_at = $1, cards_count = $2
where id = $3
`

type FinishSyncRunSuccessParams struct {
	BulkUpdatedAt *time.Time
	CardsCount    *int32
	ID            int64
}

func (q *Queries) FinishSyncRunSuccess(ctx context.Context, arg FinishSyncRunSuccessParams) error {
	_, err := q.db.Exec(ctx, finishSyncRunSuccess, arg.BulkUpdatedAt, arg.CardsCount, arg.ID)
	return err
}

const getLastSucceededSyncRun = `-- name: GetLastSucceededSyncRun :one
select id, started_at, finished_at, status, bulk_updated_at, cards_count, error from card_sync_runs where status = 'succeeded' order by id desc limit 1
`

func (q *Queries) GetLastSucceededSyncRun(ctx context.Context) (CardSyncRun, error) {
	row := q.db.QueryRow(ctx, getLastSucceededSyncRun)
	var i CardSyncRun
	err := row.Scan(
		&i.ID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Status,
		&i.BulkUpdatedAt,
		&i.CardsCount,
		&i.Error,
	)
	return i, err
}

const getPrintingsByOracleID = `-- name: GetPrintingsByOracleID :many
select scryfall_id, oracle_id, name, normalized_name, released_at, set_code, set_name, collector_number, rarity, layout, mana_cost, cmc, type_line, oracle_text, colors, color_identity, promo, image_small, image_normal, back_image_small, back_image_normal, updated_at from cards
where oracle_id = $1
order by released_at desc, set_code asc, collector_number asc
`

func (q *Queries) GetPrintingsByOracleID(ctx context.Context, oracleID uuid.UUID) ([]Card, error) {
	rows, err := q.db.Query(ctx, getPrintingsByOracleID, oracleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Card
	for rows.Next() {
		var i Card
		if err := rows.Scan(
			&i.ScryfallID,
			&i.OracleID,
			&i.Name,
			&i.NormalizedName,
			&i.ReleasedAt,
			&i.SetCode,
			&i.SetName,
			&i.CollectorNumber,
			&i.Rarity,
			&i.Layout,
			&i.ManaCost,
			&i.Cmc,
			&i.TypeLine,
			&i.OracleText,
			&i.Colors,
			&i.ColorIdentity,
			&i.Promo,
			&i.ImageSmall,
			&i.ImageNormal,
			&i.BackImageSmall,
			&i.BackImageNormal,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchCards = `-- name: SearchCards :many
with matches as (
    select distinct on (oracle_id) scryfall_id, oracle_id, name, normalized_name, released_at, set_code, set_name, collector_number, rarity, layout, mana_cost, cmc, type_line, oracle_text, colors, color_identity, promo, image_small, image_normal, back_image_small, back_image_normal, updated_at
    from cards
    where ($1::text is null
           or normalized_name like $4 || '%'
           or $1::text <% normalized_name)
      and ($5::text[] is null or color_identity <@ $5::text[])
      and ($6::text is null or type_line ilike '%' || $6 || '%')
      and ($7::float8 is null or cmc >= $7)
      and ($8::float8 is null or cmc <= $8)
      and ($9::text is null or rarity = $9)
      and ($10::text is null or set_code = $10)
    order by oracle_id, promo, released_at desc, (image_small is null)
)
select scryfall_id, oracle_id, name, normalized_name, released_at, set_code, set_name, collector_number, rarity, layout, mana_cost, cmc, type_line, oracle_text, colors, color_identity, promo, image_small, image_normal, back_image_small, back_image_normal, updated_at, count(*) over () as total
from matches
order by
    case when $1::text is not null
         then word_similarity($1, normalized_name) end desc nulls last,
    case when $1::text is not null
         then similarity($1, normalized_name) end desc nulls last,
    name asc
limit $3::int offset $2::int
`

type SearchCardsParams struct {
	Name       *string
	PageOffset int32
	PageLimit  int32
	NamePrefix *string
	Colors     []string
	CardType   *string
	CmcMin     *float64
	CmcMax     *float64
	Rarity     *string
	SetCode    *string
}

type SearchCardsRow struct {
	ScryfallID      uuid.UUID
	OracleID        uuid.UUID
	Name            string
	NormalizedName  string
	ReleasedAt      time.Time
	SetCode         string
	SetName         string
	CollectorNumber string
	Rarity          string
	Layout          string
	ManaCost        string
	Cmc             float64
	TypeLine        string
	OracleText      string
	Colors          []string
	ColorIdentity   []string
	Promo           bool
	ImageSmall      *string
	ImageNormal     *string
	BackImageSmall  *string
	BackImageNormal *string
	UpdatedAt       time.Time
	Total           int64
}

// Filtered search, AND-combined, all filters optional. colors implements
// cube semantics: color_identity ⊆ selected (empty array = colorless only).
// total is a window count over the filtered oracle-level set.
func (q *Queries) SearchCards(ctx context.Context, arg SearchCardsParams) ([]SearchCardsRow, error) {
	rows, err := q.db.Query(
		ctx, searchCards,
		arg.Name,
		arg.PageOffset,
		arg.PageLimit,
		arg.NamePrefix,
		arg.Colors,
		arg.CardType,
		arg.CmcMin,
		arg.CmcMax,
		arg.Rarity,
		arg.SetCode,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchCardsRow
	for rows.Next() {
		var i SearchCardsRow
		if err := rows.Scan(
			&i.ScryfallID,
			&i.OracleID,
			&i.Name,
			&i.NormalizedName,
			&i.ReleasedAt,
			&i.SetCode,
			&i.SetName,
			&i.CollectorNumber,
			&i.Rarity,
			&i.Layout,
			&i.ManaCost,
			&i.Cmc,
			&i.TypeLine,
			&i.OracleText,
			&i.Colors,
			&i.ColorIdentity,
			&i.Promo,
			&i.ImageSmall,
			&i.ImageNormal,
			&i.BackImageSmall,
			&i.BackImageNormal,
			&i.UpdatedAt,
			&i.Total,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const truncateCardsStaging = `-- name: TruncateCardsStaging :exec
truncate cards_staging
`

func (q *Queries) TruncateCardsStaging(ctx context.Context) error {
	_, err := q.db.Exec(ctx, truncateCardsStaging)
	return err
}

const upsertCardsFromStaging = `-- name: UpsertCardsFromStaging :execrows
insert into cards (
    scryfall_id, oracle_id, name, normalized_name, released_at, set_code,
    set_name, collector_number, rarity, layout, mana_cost, cmc, type_line,
    oracle_text, colors, color_identity, promo, image_small, image_normal,
    back_image_small, back_image_normal, updated_at
)
select scryfall_id, oracle_id, name, normalized_name, released_at, set_code,
    set_name, collector_number, rarity, layout, mana_cost, cmc, type_line,
    oracle_text, colors, color_identity, promo, image_small, image_normal,
    back_image_small, back_image_normal, now()
from cards_staging
on conflict (scryfall_id) do update set
    oracle_id = excluded.oracle_id,
    name = excluded.name,
    normalized_name = excluded.normalized_name,
    released_at = excluded.released_at,
    set_code = excluded.set_code,
    set_name = excluded.set_name,
    collector_number = excluded.collector_number,
    rarity = excluded.rarity,
    layout = excluded.layout,
    mana_cost = excluded.mana_cost,
    cmc = excluded.cmc,
    type_line = excluded.type_line,
    oracle_text = excluded.oracle_text,
    colors = excluded.colors,
    color_identity = excluded.color_identity,
    promo = excluded.promo,
    image_small = excluded.image_small,
    image_normal = excluded.image_normal,
    back_image_small = excluded.back_image_small,
    back_image_normal = excluded.back_image_normal,
    updated_at = now()
`

func (q *Queries) UpsertCardsFromStaging(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, upsertCardsFromStaging)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
