// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cards.sql

package db

import (
	"context"
	"time"
)

const countCards = `-- name: CountCards :one
select count(*) from cards
`

func (q *Queries) CountCards(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countCards)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSyncRun = `-- name: CreateSyncRun :one
insert into card_sync_runs (status) values ('running') returning id
`

func (q *Queries) CreateSyncRun(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, createSyncRun)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deleteCardsMissingFromStaging = `-- name: DeleteCardsMissingFromStaging :execrows
delete from cards
where scryfall_id not in (select scryfall_id from cards_staging)
`

func (q *Queries) DeleteCardsMissingFromStaging(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCardsMissingFromStaging)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const failStaleRunningSyncRuns = `-- name: FailStaleRunningSyncRuns :exec
update card_sync_runs
set status = 'failed', finished_at = now(), error = 'interrupted (process restart)'
where status = 'running'
`

func (q *Queries) FailStaleRunningSyncRuns(ctx context.Context) error {
	_, err := q.db.Exec(ctx, failStaleRunningSyncRuns)
	return err
}

const finishSyncRunFailure = `-- name: FinishSyncRunFailure :exec
update card_sync_runs
set status = 'failed', finished_at = now(), error = $1
where id = $2
`

type FinishSyncRunFailureParams struct {
	Error *string
	ID    int64
}

func (q *Queries) FinishSyncRunFailure(ctx context.Context, arg FinishSyncRunFailureParams) error {
	_, err := q.db.Exec(ctx, finishSyncRunFailure, arg.Error, arg.ID)
	return err
}

const finishSyncRunSuccess = `-- name: FinishSyncRunSuccess :exec
update card_sync_runs
set status = 'succeeded', finished_at = now(),
    bulk_updated_at = $1, cards_count = $2
where id = $3
`

type FinishSyncRunSuccessParams struct {
	BulkUpdatedAt *time.Time
	CardsCount    *int32
	ID            int64
}

func (q *Queries) FinishSyncRunSuccess(ctx context.Context, arg FinishSyncRunSuccessParams) error {
	_, err := q.db.Exec(ctx, finishSyncRunSuccess, arg.BulkUpdatedAt, arg.CardsCount, arg.ID)
	return err
}

const getLastSucceededSyncRun = `-- name: GetLastSucceededSyncRun :one
select id, started_at, finished_at, status, bulk_updated_at, cards_count, error from card_sync_runs where status = 'succeeded' order by id desc limit 1
`

func (q *Queries) GetLastSucceededSyncRun(ctx context.Context) (CardSyncRun, error) {
	row := q.db.QueryRow(ctx, getLastSucceededSyncRun)
	var i CardSyncRun
	err := row.Scan(
		&i.ID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Status,
		&i.BulkUpdatedAt,
		&i.CardsCount,
		&i.Error,
	)
	return i, err
}

const truncateCardsStaging = `-- name: TruncateCardsStaging :exec
truncate cards_staging
`

func (q *Queries) TruncateCardsStaging(ctx context.Context) error {
	_, err := q.db.Exec(ctx, truncateCardsStaging)
	return err
}

const upsertCardsFromStaging = `-- name: UpsertCardsFromStaging :execrows
insert into cards (
    scryfall_id, oracle_id, name, normalized_name, released_at, set_code,
    set_name, collector_number, rarity, layout, mana_cost, cmc, type_line,
    oracle_text, colors, color_identity, promo, image_small, image_normal,
    back_image_small, back_image_normal, updated_at
)
select scryfall_id, oracle_id, name, normalized_name, released_at, set_code,
    set_name, collector_number, rarity, layout, mana_cost, cmc, type_line,
    oracle_text, colors, color_identity, promo, image_small, image_normal,
    back_image_small, back_image_normal, now()
from cards_staging
on conflict (scryfall_id) do update set
    oracle_id = excluded.oracle_id,
    name = excluded.name,
    normalized_name = excluded.normalized_name,
    released_at = excluded.released_at,
    set_code = excluded.set_code,
    set_name = excluded.set_name,
    collector_number = excluded.collector_number,
    rarity = excluded.rarity,
    layout = excluded.layout,
    mana_cost = excluded.mana_cost,
    cmc = excluded.cmc,
    type_line = excluded.type_line,
    oracle_text = excluded.oracle_text,
    colors = excluded.colors,
    color_identity = excluded.color_identity,
    promo = excluded.promo,
    image_small = excluded.image_small,
    image_normal = excluded.image_normal,
    back_image_small = excluded.back_image_small,
    back_image_normal = excluded.back_image_normal,
    updated_at = now()
`

func (q *Queries) UpsertCardsFromStaging(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, upsertCardsFromStaging)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
