// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: collections.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const addCollectionItem = `-- name: AddCollectionItem :exec
insert into collection_items (user_id, scryfall_id, oracle_id, quantity)
select $1, c.scryfall_id, c.oracle_id, least($2::int, 999)
from cards c
where c.scryfall_id = $3
on conflict (user_id, scryfall_id)
do update set
    quantity = least(collection_items.quantity + excluded.quantity, 999),
    updated_at = now()
`

type AddCollectionItemParams struct {
	UserID     uuid.UUID
	Quantity   int32
	ScryfallID uuid.UUID
}

// Add-quantity upsert (import + change-printing merge). 999 is the hard
// per-printing maximum everywhere, so results clamp instead of erroring.
func (q *Queries) AddCollectionItem(ctx context.Context, arg AddCollectionItemParams) error {
	_, err := q.db.Exec(ctx, addCollectionItem, arg.UserID, arg.Quantity, arg.ScryfallID)
	return err
}

const deleteCollectionItem = `-- name: DeleteCollectionItem :execrows
delete from collection_items
where user_id = $1 and scryfall_id = $2
`

type DeleteCollectionItemParams struct {
	UserID     uuid.UUID
	ScryfallID uuid.UUID
}

func (q *Queries) DeleteCollectionItem(ctx context.Context, arg DeleteCollectionItemParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCollectionItem, arg.UserID, arg.ScryfallID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCardsByNormalizedNames = `-- name: GetCardsByNormalizedNames :many
with matches as (
    select distinct on (oracle_id) scryfall_id, oracle_id, name, normalized_name, released_at, set_code, set_name, collector_number, rarity, layout, mana_cost, cmc, type_line, oracle_text, colors, color_identity, promo, image_small, image_normal, back_image_small, back_image_normal, updated_at
    from cards
    where normalized_name = any($1::text[])
    order by oracle_id, promo, released_at desc, (image_small is null)
)
select scryfall_id, oracle_id, name, normalized_name, mana_cost, type_line,
    set_code, set_name, collector_number, image_small, image_normal
from matches
`

type GetCardsByNormalizedNamesRow struct {
	ScryfallID      uuid.UUID
	OracleID        uuid.UUID
	Name            string
	NormalizedName  string
	ManaCost        string
	TypeLine        string
	SetCode         string
	SetName         string
	CollectorNumber string
	ImageSmall      *string
	ImageNormal     *string
}

// Exact-name resolution for import: representative printing per oracle
// card (same non-promo/newest/has-image rule as autocomplete). Several
// oracle cards sharing one name all come back — the service treats that
// name as ambiguous.
func (q *Queries) GetCardsByNormalizedNames(ctx context.Context, names []string) ([]GetCardsByNormalizedNamesRow, error) {
	rows, err := q.db.Query(ctx, getCardsByNormalizedNames, names)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCardsByNormalizedNamesRow
	for rows.Next() {
		var i GetCardsByNormalizedNamesRow
		if err := rows.Scan(
			&i.ScryfallID,
			&i.OracleID,
			&i.Name,
			&i.NormalizedName,
			&i.ManaCost,
			&i.TypeLine,
			&i.SetCode,
			&i.SetName,
			&i.CollectorNumber,
			&i.ImageSmall,
			&i.ImageNormal,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCollectionItemEntry = `-- name: GetCollectionItemEntry :one
select ci.scryfall_id, ci.oracle_id, ci.quantity,
    ca.name, ca.mana_cost, ca.type_line, ca.set_code, ca.set_name,
    ca.collector_number, ca.image_small, ca.image_normal
from collection_items ci
join cards ca on ca.scryfall_id = ci.scryfall_id
where ci.user_id = $1 and ci.scryfall_id = $2
`

type GetCollectionItemEntryParams struct {
	UserID     uuid.UUID
	ScryfallID uuid.UUID
}

type GetCollectionItemEntryRow struct {
	ScryfallID      uuid.UUID
	OracleID        uuid.UUID
	Quantity        int32
	Name            string
	ManaCost        string
	TypeLine        string
	SetCode         string
	SetName         string
	CollectorNumber string
	ImageSmall      *string
	ImageNormal     *string
}

// One item with display data (PUT / change-printing responses).
func (q *Queries) GetCollectionItemEntry(ctx context.Context, arg GetCollectionItemEntryParams) (GetCollectionItemEntryRow, error) {
	row := q.db.QueryRow(ctx, getCollectionItemEntry, arg.UserID, arg.ScryfallID)
	var i GetCollectionItemEntryRow
	err := row.Scan(
		&i.ScryfallID,
		&i.OracleID,
		&i.Quantity,
		&i.Name,
		&i.ManaCost,
		&i.TypeLine,
		&i.SetCode,
		&i.SetName,
		&i.CollectorNumber,
		&i.ImageSmall,
		&i.ImageNormal,
	)
	return i, err
}

const getCollectionItemForUpdate = `-- name: GetCollectionItemForUpdate :one
select user_id, scryfall_id, oracle_id, quantity, created_at, updated_at from collection_items
where user_id = $1 and scryfall_id = $2
for update
`

type GetCollectionItemForUpdateParams struct {
	UserID     uuid.UUID
	ScryfallID uuid.UUID
}

// Locks the source row for the change-printing transaction.
func (q *Queries) GetCollectionItemForUpdate(ctx context.Context, arg GetCollectionItemForUpdateParams) (CollectionItem, error) {
	row := q.db.QueryRow(ctx, getCollectionItemForUpdate, arg.UserID, arg.ScryfallID)
	var i CollectionItem
	err := row.Scan(
		&i.UserID,
		&i.ScryfallID,
		&i.OracleID,
		&i.Quantity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCubeWantlist = `-- name: GetCubeWantlist :many
select cc.oracle_id, cc.scryfall_id,
    cc.quantity as cube_quantity,
    coalesce(own.owned, 0)::int as owned_quantity,
    (cc.quantity - coalesce(own.owned, 0))::int as missing_quantity,
    ca.name, ca.mana_cost, ca.image_small, ca.image_normal
from cube_cards cc
join cards ca on ca.scryfall_id = cc.scryfall_id
left join (
    select oracle_id, sum(quantity)::int as owned
    from collection_items
    where user_id = $1
    group by oracle_id
) own on own.oracle_id = cc.oracle_id
where cc.cube_id = $2
  and cc.quantity > coalesce(own.owned, 0)
order by ca.name
`

type GetCubeWantlistParams struct {
	UserID uuid.UUID
	CubeID uuid.UUID
}

type GetCubeWantlistRow struct {
	OracleID        uuid.UUID
	ScryfallID      uuid.UUID
	CubeQuantity    int32
	OwnedQuantity   int32
	MissingQuantity int32
	Name            string
	ManaCost        string
	ImageSmall      *string
	ImageNormal     *string
}

// Wantlist: per cube row (already oracle-level), missing = cube quantity
// minus the user's copies of that oracle across all printings, rows with
// missing > 0 only. Computed on demand, never stored.
func (q *Queries) GetCubeWantlist(ctx context.Context, arg GetCubeWantlistParams) ([]GetCubeWantlistRow, error) {
	rows, err := q.db.Query(ctx, getCubeWantlist, arg.UserID, arg.CubeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCubeWantlistRow
	for rows.Next() {
		var i GetCubeWantlistRow
		if err := rows.Scan(
			&i.OracleID,
			&i.ScryfallID,
			&i.CubeQuantity,
			&i.OwnedQuantity,
			&i.MissingQuantity,
			&i.Name,
			&i.ManaCost,
			&i.ImageSmall,
			&i.ImageNormal,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOwnedScryfallIDs = `-- name: GetOwnedScryfallIDs :many
select scryfall_id from collection_items
where user_id = $1 and scryfall_id = any($2::uuid[])
`

type GetOwnedScryfallIDsParams struct {
	UserID uuid.UUID
	Ids    []uuid.UUID
}

// Which of these printings does the user already own? (import summary)
func (q *Queries) GetOwnedScryfallIDs(ctx context.Context, arg GetOwnedScryfallIDsParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, getOwnedScryfallIDs, arg.UserID, arg.Ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var scryfall_id uuid.UUID
		if err := rows.Scan(&scryfall_id); err != nil {
			return nil, err
		}
		items = append(items, scryfall_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCollectionItems = `-- name: ListCollectionItems :many
select ci.scryfall_id, ci.oracle_id, ci.quantity,
    ca.name, ca.mana_cost, ca.type_line, ca.set_code, ca.set_name,
    ca.collector_number, ca.image_small, ca.image_normal,
    count(*) over () as total,
    sum(ci.quantity) over ()::bigint as total_copies
from collection_items ci
join cards ca on ca.scryfall_id = ci.scryfall_id
where ci.user_id = $1
  and ($2::text is null or ca.name ilike '%' || $2 || '%')
order by ca.name, ca.set_code, ca.collector_number
limit $4::int offset $3::int
`

type ListCollectionItemsParams struct {
	UserID     uuid.UUID
	Search     *string
	PageOffset int32
	PageLimit  int32
}

type ListCollectionItemsRow struct {
	ScryfallID      uuid.UUID
	OracleID        uuid.UUID
	Quantity        int32
	Name            string
	ManaCost        string
	TypeLine        string
	SetCode         string
	SetName         string
	CollectorNumber string
	ImageSmall      *string
	ImageNormal     *string
	Total           int64
	TotalCopies     int64
}

// The session user's collection, name-sorted, with display data and
// window totals (distinct rows + summed copies) over the filtered set.
// Plain ILIKE is enough at collection scale — no trigram machinery.
func (q *Queries) ListCollectionItems(ctx context.Context, arg ListCollectionItemsParams) ([]ListCollectionItemsRow, error) {
	rows, err := q.db.Query(
		ctx, listCollectionItems,
		arg.UserID,
		arg.Search,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCollectionItemsRow
	for rows.Next() {
		var i ListCollectionItemsRow
		if err := rows.Scan(
			&i.ScryfallID,
			&i.OracleID,
			&i.Quantity,
			&i.Name,
			&i.ManaCost,
			&i.TypeLine,
			&i.SetCode,
			&i.SetName,
			&i.CollectorNumber,
			&i.ImageSmall,
			&i.ImageNormal,
			&i.Total,
			&i.TotalCopies,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const suggestCardsByName = `-- name: SuggestCardsByName :many
with matches as (
    select distinct on (oracle_id) scryfall_id, oracle_id, name, normalized_name, released_at, set_code, set_name, collector_number, rarity, layout, mana_cost, cmc, type_line, oracle_text, colors, color_identity, promo, image_small, image_normal, back_image_small, back_image_normal, updated_at
    from cards
    where $1::text <% normalized_name
    order by oracle_id, promo, released_at desc, (image_small is null)
)
select scryfall_id, oracle_id, name, mana_cost, type_line,
    set_code, set_name, collector_number, image_small, image_normal
from matches
order by
    word_similarity($1, normalized_name) desc,
    similarity($1, normalized_name) desc,
    name asc
limit 5
`

type SuggestCardsByNameRow struct {
	ScryfallID      uuid.UUID
	OracleID        uuid.UUID
	Name            string
	ManaCost        string
	TypeLine        string
	SetCode         string
	SetName         string
	CollectorNumber string
	ImageSmall      *string
	ImageNormal     *string
}

// Fuzzy suggestions for one unresolved import line. Same <% + GUC
// threshold setup as autocomplete (see cards.sql for why the operator
// form matters); oracle-level with a representative printing.
func (q *Queries) SuggestCardsByName(ctx context.Context, query string) ([]SuggestCardsByNameRow, error) {
	rows, err := q.db.Query(ctx, suggestCardsByName, query)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SuggestCardsByNameRow
	for rows.Next() {
		var i SuggestCardsByNameRow
		if err := rows.Scan(
			&i.ScryfallID,
			&i.OracleID,
			&i.Name,
			&i.ManaCost,
			&i.TypeLine,
			&i.SetCode,
			&i.SetName,
			&i.CollectorNumber,
			&i.ImageSmall,
			&i.ImageNormal,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertCollectionItem = `-- name: UpsertCollectionItem :one
insert into collection_items (user_id, scryfall_id, oracle_id, quantity)
select $1, c.scryfall_id, c.oracle_id, $2
from cards c
where c.scryfall_id = $3
on conflict (user_id, scryfall_id)
do update set quantity = excluded.quantity, updated_at = now()
returning user_id, scryfall_id, oracle_id, quantity, created_at, updated_at
`

type UpsertCollectionItemParams struct {
	UserID     uuid.UUID
	Quantity   int32
	ScryfallID uuid.UUID
}

// Set-quantity upsert. Selecting from cards resolves oracle_id at write
// time AND makes an unknown printing insert zero rows (pgx.ErrNoRows on
// :one), which the service maps to the invalid-item error.
func (q *Queries) UpsertCollectionItem(ctx context.Context, arg UpsertCollectionItemParams) (CollectionItem, error) {
	row := q.db.QueryRow(ctx, upsertCollectionItem, arg.UserID, arg.Quantity, arg.ScryfallID)
	var i CollectionItem
	err := row.Scan(
		&i.UserID,
		&i.ScryfallID,
		&i.OracleID,
		&i.Quantity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
