// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cubes.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const addCubeCard = `-- name: AddCubeCard :exec
insert into cube_cards (cube_id, oracle_id, scryfall_id, quantity)
values ($1, $2, $3, $4)
on conflict (cube_id, oracle_id)
do update set quantity = cube_cards.quantity + excluded.quantity
`

type AddCubeCardParams struct {
	CubeID     uuid.UUID
	OracleID   uuid.UUID
	ScryfallID uuid.UUID
	Quantity   int32
}

// Add: insert or increment. On increment the existing printing wins —
// excluded.scryfall_id is deliberately ignored.
func (q *Queries) AddCubeCard(ctx context.Context, arg AddCubeCardParams) error {
	_, err := q.db.Exec(
		ctx, addCubeCard,
		arg.CubeID,
		arg.OracleID,
		arg.ScryfallID,
		arg.Quantity,
	)
	return err
}

const bumpCubeVersion = `-- name: BumpCubeVersion :exec
update cubes set version = version + 1, updated_at = now() where id = $1
`

func (q *Queries) BumpCubeVersion(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, bumpCubeVersion, id)
	return err
}

const createCube = `-- name: CreateCube :one
insert into cubes (owner_id, name, description, visibility)
values ($1, $2, $3, $4)
returning id, owner_id, name, description, visibility, version, created_at, updated_at
`

type CreateCubeParams struct {
	OwnerID     uuid.UUID
	Name        string
	Description string
	Visibility  string
}

func (q *Queries) CreateCube(ctx context.Context, arg CreateCubeParams) (Cube, error) {
	row := q.db.QueryRow(
		ctx, createCube,
		arg.OwnerID,
		arg.Name,
		arg.Description,
		arg.Visibility,
	)
	var i Cube
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Description,
		&i.Visibility,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCube = `-- name: DeleteCube :exec
delete from cubes where id = $1
`

func (q *Queries) DeleteCube(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteCube, id)
	return err
}

const deleteDepletedCubeCards = `-- name: DeleteDepletedCubeCards :exec
delete from cube_cards where cube_id = $1 and quantity <= 0
`

func (q *Queries) DeleteDepletedCubeCards(ctx context.Context, cubeID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteDepletedCubeCards, cubeID)
	return err
}

const getCardsByScryfallIDs = `-- name: GetCardsByScryfallIDs :many
select scryfall_id, oracle_id, name
from cards
where scryfall_id = any($1::uuid[])
`

type GetCardsByScryfallIDsRow struct {
	ScryfallID uuid.UUID
	OracleID   uuid.UUID
	Name       string
}

// Resolve add-inputs (scryfall id) to oracle identity.
func (q *Queries) GetCardsByScryfallIDs(ctx context.Context, ids []uuid.UUID) ([]GetCardsByScryfallIDsRow, error) {
	rows, err := q.db.Query(ctx, getCardsByScryfallIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCardsByScryfallIDsRow
	for rows.Next() {
		var i GetCardsByScryfallIDsRow
		if err := rows.Scan(&i.ScryfallID, &i.OracleID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCardsDisplayByScryfallIDs = `-- name: GetCardsDisplayByScryfallIDs :many
select scryfall_id, oracle_id, name, mana_cost, type_line, cmc, colors,
    color_identity, rarity, image_small, image_normal
from cards
where scryfall_id = any($1::uuid[])
`

type GetCardsDisplayByScryfallIDsRow struct {
	ScryfallID    uuid.UUID
	OracleID      uuid.UUID
	Name          string
	ManaCost      string
	TypeLine      string
	Cmc           float64
	Colors        []string
	ColorIdentity []string
	Rarity        string
	ImageSmall    *string
	ImageNormal   *string
}

// Display data for reconstructed past states.
func (q *Queries) GetCardsDisplayByScryfallIDs(ctx context.Context, ids []uuid.UUID) ([]GetCardsDisplayByScryfallIDsRow, error) {
	rows, err := q.db.Query(ctx, getCardsDisplayByScryfallIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCardsDisplayByScryfallIDsRow
	for rows.Next() {
		var i GetCardsDisplayByScryfallIDsRow
		if err := rows.Scan(
			&i.ScryfallID,
			&i.OracleID,
			&i.Name,
			&i.ManaCost,
			&i.TypeLine,
			&i.Cmc,
			&i.Colors,
			&i.ColorIdentity,
			&i.Rarity,
			&i.ImageSmall,
			&i.ImageNormal,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCube = `-- name: GetCube :one
select c.id, c.owner_id, c.name, c.description, c.visibility, c.version, c.created_at, c.updated_at, u.display_name as owner_name,
    coalesce((select sum(cc.quantity) from cube_cards cc where cc.cube_id = c.id), 0)::bigint as card_count
from cubes c
join users u on u.id = c.owner_id
where c.id = $1
`

type GetCubeRow struct {
	ID          uuid.UUID
	OwnerID     uuid.UUID
	Name        string
	Description string
	Visibility  string
	Version     int32
	CreatedAt   time.Time
	UpdatedAt   time.Time
	OwnerName   string
	CardCount   int64
}

func (q *Queries) GetCube(ctx context.Context, id uuid.UUID) (GetCubeRow, error) {
	row := q.db.QueryRow(ctx, getCube, id)
	var i GetCubeRow
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Description,
		&i.Visibility,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OwnerName,
		&i.CardCount,
	)
	return i, err
}

const getCubeCardQuantities = `-- name: GetCubeCardQuantities :many
select oracle_id, scryfall_id, quantity
from cube_cards
where cube_id = $1
`

type GetCubeCardQuantitiesRow struct {
	OracleID   uuid.UUID
	ScryfallID uuid.UUID
	Quantity   int32
}

// Bare quantities for diff validation and replay.
func (q *Queries) GetCubeCardQuantities(ctx context.Context, cubeID uuid.UUID) ([]GetCubeCardQuantitiesRow, error) {
	rows, err := q.db.Query(ctx, getCubeCardQuantities, cubeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCubeCardQuantitiesRow
	for rows.Next() {
		var i GetCubeCardQuantitiesRow
		if err := rows.Scan(&i.OracleID, &i.ScryfallID, &i.Quantity); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCubeCards = `-- name: GetCubeCards :many
select cc.oracle_id, cc.scryfall_id, cc.quantity,
    ca.name, ca.mana_cost, ca.type_line, ca.cmc, ca.colors,
    ca.color_identity, ca.rarity, ca.image_small, ca.image_normal
from cube_cards cc
join cards ca on ca.scryfall_id = cc.scryfall_id
where cc.cube_id = $1
order by ca.name
`

type GetCubeCardsRow struct {
	OracleID      uuid.UUID
	ScryfallID    uuid.UUID
	Quantity      int32
	Name          string
	ManaCost      string
	TypeLine      string
	Cmc           float64
	Colors        []string
	ColorIdentity []string
	Rarity        string
	ImageSmall    *string
	ImageNormal   *string
}

// Current list with display data for the grouped view.
func (q *Queries) GetCubeCards(ctx context.Context, cubeID uuid.UUID) ([]GetCubeCardsRow, error) {
	rows, err := q.db.Query(ctx, getCubeCards, cubeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCubeCardsRow
	for rows.Next() {
		var i GetCubeCardsRow
		if err := rows.Scan(
			&i.OracleID,
			&i.ScryfallID,
			&i.Quantity,
			&i.Name,
			&i.ManaCost,
			&i.TypeLine,
			&i.Cmc,
			&i.Colors,
			&i.ColorIdentity,
			&i.Rarity,
			&i.ImageSmall,
			&i.ImageNormal,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCubeForUpdate = `-- name: GetCubeForUpdate :one
select id, owner_id, name, description, visibility, version, created_at, updated_at from cubes where id = $1 for update
`

func (q *Queries) GetCubeForUpdate(ctx context.Context, id uuid.UUID) (Cube, error) {
	row := q.db.QueryRow(ctx, getCubeForUpdate, id)
	var i Cube
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Description,
		&i.Visibility,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertCubeChange = `-- name: InsertCubeChange :one
insert into cube_changes (cube_id, version, author_id, note)
values ($1, $2, $3, $4)
returning id, cube_id, version, author_id, note, created_at
`

type InsertCubeChangeParams struct {
	CubeID   uuid.UUID
	Version  int32
	AuthorID uuid.UUID
	Note     string
}

func (q *Queries) InsertCubeChange(ctx context.Context, arg InsertCubeChangeParams) (CubeChange, error) {
	row := q.db.QueryRow(
		ctx, insertCubeChange,
		arg.CubeID,
		arg.Version,
		arg.AuthorID,
		arg.Note,
	)
	var i CubeChange
	err := row.Scan(
		&i.ID,
		&i.CubeID,
		&i.Version,
		&i.AuthorID,
		&i.Note,
		&i.CreatedAt,
	)
	return i, err
}

const insertCubeChangeItem = `-- name: InsertCubeChangeItem :exec
insert into cube_change_items (change_id, kind, oracle_id, scryfall_id, quantity)
values ($1, $2, $3, $4, $5)
`

type InsertCubeChangeItemParams struct {
	ChangeID   uuid.UUID
	Kind       string
	OracleID   uuid.UUID
	ScryfallID uuid.UUID
	Quantity   int32
}

func (q *Queries) InsertCubeChangeItem(ctx context.Context, arg InsertCubeChangeItemParams) error {
	_, err := q.db.Exec(
		ctx, insertCubeChangeItem,
		arg.ChangeID,
		arg.Kind,
		arg.OracleID,
		arg.ScryfallID,
		arg.Quantity,
	)
	return err
}

const listChangeItemsAfterVersion = `-- name: ListChangeItemsAfterVersion :many
select ch.version, ci.kind, ci.oracle_id, ci.scryfall_id, ci.quantity
from cube_changes ch
join cube_change_items ci on ci.change_id = ch.id
where ch.cube_id = $1 and ch.version > $2
order by ch.version desc
`

type ListChangeItemsAfterVersionParams struct {
	CubeID       uuid.UUID
	AfterVersion int32
}

type ListChangeItemsAfterVersionRow struct {
	Version    int32
	Kind       string
	OracleID   uuid.UUID
	ScryfallID uuid.UUID
	Quantity   int32
}

// Replay input: items of every change newer than after_version, newest
// change first.
func (q *Queries) ListChangeItemsAfterVersion(ctx context.Context, arg ListChangeItemsAfterVersionParams) ([]ListChangeItemsAfterVersionRow, error) {
	rows, err := q.db.Query(ctx, listChangeItemsAfterVersion, arg.CubeID, arg.AfterVersion)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListChangeItemsAfterVersionRow
	for rows.Next() {
		var i ListChangeItemsAfterVersionRow
		if err := rows.Scan(
			&i.Version,
			&i.Kind,
			&i.OracleID,
			&i.ScryfallID,
			&i.Quantity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChangeItemsForChanges = `-- name: ListChangeItemsForChanges :many
select ci.change_id, ci.kind, ci.oracle_id, ci.quantity, ca.name
from cube_change_items ci
join cards ca on ca.scryfall_id = ci.scryfall_id
where ci.change_id = any($1::uuid[])
order by ca.name
`

type ListChangeItemsForChangesRow struct {
	ChangeID uuid.UUID
	Kind     string
	OracleID uuid.UUID
	Quantity int32
	Name     string
}

func (q *Queries) ListChangeItemsForChanges(ctx context.Context, changeIds []uuid.UUID) ([]ListChangeItemsForChangesRow, error) {
	rows, err := q.db.Query(ctx, listChangeItemsForChanges, changeIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListChangeItemsForChangesRow
	for rows.Next() {
		var i ListChangeItemsForChangesRow
		if err := rows.Scan(
			&i.ChangeID,
			&i.Kind,
			&i.OracleID,
			&i.Quantity,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCubeChanges = `-- name: ListCubeChanges :many
select ch.id, ch.cube_id, ch.version, ch.author_id, ch.note, ch.created_at, u.display_name as author_name, count(*) over () as total
from cube_changes ch
join users u on u.id = ch.author_id
where ch.cube_id = $1
order by ch.version desc
limit $3::int offset $2::int
`

type ListCubeChangesParams struct {
	CubeID     uuid.UUID
	PageOffset int32
	PageLimit  int32
}

type ListCubeChangesRow struct {
	ID         uuid.UUID
	CubeID     uuid.UUID
	Version    int32
	AuthorID   uuid.UUID
	Note       string
	CreatedAt  time.Time
	AuthorName string
	Total      int64
}

func (q *Queries) ListCubeChanges(ctx context.Context, arg ListCubeChangesParams) ([]ListCubeChangesRow, error) {
	rows, err := q.db.Query(ctx, listCubeChanges, arg.CubeID, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCubeChangesRow
	for rows.Next() {
		var i ListCubeChangesRow
		if err := rows.Scan(
			&i.ID,
			&i.CubeID,
			&i.Version,
			&i.AuthorID,
			&i.Note,
			&i.CreatedAt,
			&i.AuthorName,
			&i.Total,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMyCubes = `-- name: ListMyCubes :many
select c.id, c.owner_id, c.name, c.description, c.visibility, c.version, c.created_at, c.updated_at, u.display_name as owner_name,
    coalesce((select sum(cc.quantity) from cube_cards cc where cc.cube_id = c.id), 0)::bigint as card_count
from cubes c
join users u on u.id = c.owner_id
where c.owner_id = $1
order by c.updated_at desc
`

type ListMyCubesRow struct {
	ID          uuid.UUID
	OwnerID     uuid.UUID
	Name        string
	Description string
	Visibility  string
	Version     int32
	CreatedAt   time.Time
	UpdatedAt   time.Time
	OwnerName   string
	CardCount   int64
}

func (q *Queries) ListMyCubes(ctx context.Context, ownerID uuid.UUID) ([]ListMyCubesRow, error) {
	rows, err := q.db.Query(ctx, listMyCubes, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMyCubesRow
	for rows.Next() {
		var i ListMyCubesRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Name,
			&i.Description,
			&i.Visibility,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OwnerName,
			&i.CardCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublicCubes = `-- name: ListPublicCubes :many
select c.id, c.owner_id, c.name, c.description, c.visibility, c.version, c.created_at, c.updated_at, u.display_name as owner_name,
    coalesce((select sum(cc.quantity) from cube_cards cc where cc.cube_id = c.id), 0)::bigint as card_count,
    count(*) over () as total
from cubes c
join users u on u.id = c.owner_id
where c.visibility = 'public'
  and ($1::text is null or $1::text <% c.name)
order by c.updated_at desc
limit $3::int offset $2::int
`

type ListPublicCubesParams struct {
	Query      *string
	PageOffset int32
	PageLimit  int32
}

type ListPublicCubesRow struct {
	ID          uuid.UUID
	OwnerID     uuid.UUID
	Name        string
	Description string
	Visibility  string
	Version     int32
	CreatedAt   time.Time
	UpdatedAt   time.Time
	OwnerName   string
	CardCount   int64
	Total       int64
}

// Browser: public cubes, newest-updated first, optional trgm name search.
// pg_trgm lowercases trigrams, so matching is case-insensitive as-is.
func (q *Queries) ListPublicCubes(ctx context.Context, arg ListPublicCubesParams) ([]ListPublicCubesRow, error) {
	rows, err := q.db.Query(ctx, listPublicCubes, arg.Query, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPublicCubesRow
	for rows.Next() {
		var i ListPublicCubesRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Name,
			&i.Description,
			&i.Visibility,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OwnerName,
			&i.CardCount,
			&i.Total,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeCubeCardQuantity = `-- name: RemoveCubeCardQuantity :exec
update cube_cards
set quantity = quantity - $1
where cube_id = $2 and oracle_id = $3
`

type RemoveCubeCardQuantityParams struct {
	Quantity int32
	CubeID   uuid.UUID
	OracleID uuid.UUID
}

func (q *Queries) RemoveCubeCardQuantity(ctx context.Context, arg RemoveCubeCardQuantityParams) error {
	_, err := q.db.Exec(ctx, removeCubeCardQuantity, arg.Quantity, arg.CubeID, arg.OracleID)
	return err
}

const updateCubeMeta = `-- name: UpdateCubeMeta :exec
update cubes set
    name = coalesce($1, name),
    description = coalesce($2, description),
    visibility = coalesce($3, visibility),
    updated_at = now()
where id = $4
`

type UpdateCubeMetaParams struct {
	Name        *string
	Description *string
	Visibility  *string
	ID          uuid.UUID
}

func (q *Queries) UpdateCubeMeta(ctx context.Context, arg UpdateCubeMetaParams) error {
	_, err := q.db.Exec(
		ctx, updateCubeMeta,
		arg.Name,
		arg.Description,
		arg.Visibility,
		arg.ID,
	)
	return err
}
