// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: events.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countOccupiedSpots = `-- name: CountOccupiedSpots :one
select count(*) from registrations
where event_id = $1 and status in ('pending_payment', 'paid')
`

// Capacity = pending_payment + paid (spec §2).
func (q *Queries) CountOccupiedSpots(ctx context.Context, eventID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countOccupiedSpots, eventID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createEvent = `-- name: CreateEvent :one
insert into events (organizer_id, name, description, location, starts_at,
    fee_cents, currency, max_participants, refund_deadline)
values ($1, $2, $3,
    $4, $5, $6,
    $7, $8, $9)
returning id, organizer_id, name, description, location, starts_at, fee_cents, currency, max_participants, refund_deadline, status, waitlist_counter, created_at, updated_at
`

type CreateEventParams struct {
	OrganizerID     uuid.UUID
	Name            string
	Description     string
	Location        string
	StartsAt        time.Time
	FeeCents        int32
	Currency        string
	MaxParticipants int32
	RefundDeadline  *time.Time
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error) {
	row := q.db.QueryRow(
		ctx, createEvent,
		arg.OrganizerID,
		arg.Name,
		arg.Description,
		arg.Location,
		arg.StartsAt,
		arg.FeeCents,
		arg.Currency,
		arg.MaxParticipants,
		arg.RefundDeadline,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.OrganizerID,
		&i.Name,
		&i.Description,
		&i.Location,
		&i.StartsAt,
		&i.FeeCents,
		&i.Currency,
		&i.MaxParticipants,
		&i.RefundDeadline,
		&i.Status,
		&i.WaitlistCounter,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createRegistration = `-- name: CreateRegistration :one
insert into registrations (event_id, user_id, status, expires_at, waitlist_pos, paid_at)
values ($1, $2, $3,
    $4, $5, $6)
returning id, event_id, user_id, status, expires_at, waitlist_pos, stripe_checkout_session_id, stripe_checkout_session_url, stripe_session_expires_at, stripe_payment_intent_id, paid_at, created_at, updated_at
`

type CreateRegistrationParams struct {
	EventID     uuid.UUID
	UserID      uuid.UUID
	Status      string
	ExpiresAt   *time.Time
	WaitlistPos *int64
	PaidAt      *time.Time
}

func (q *Queries) CreateRegistration(ctx context.Context, arg CreateRegistrationParams) (Registration, error) {
	row := q.db.QueryRow(
		ctx, createRegistration,
		arg.EventID,
		arg.UserID,
		arg.Status,
		arg.ExpiresAt,
		arg.WaitlistPos,
		arg.PaidAt,
	)
	var i Registration
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.UserID,
		&i.Status,
		&i.ExpiresAt,
		&i.WaitlistPos,
		&i.StripeCheckoutSessionID,
		&i.StripeCheckoutSessionUrl,
		&i.StripeSessionExpiresAt,
		&i.StripePaymentIntentID,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteEventCubes = `-- name: DeleteEventCubes :exec
delete from event_cubes where event_id = $1
`

func (q *Queries) DeleteEventCubes(ctx context.Context, eventID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteEventCubes, eventID)
	return err
}

const expireOverduePendingForEvent = `-- name: ExpireOverduePendingForEvent :many
update registrations set status = 'expired',
    expires_at = null, waitlist_pos = null, updated_at = now()
where event_id = $1 and status = 'pending_payment'
    and expires_at <= $2
    and (stripe_session_expires_at is null or stripe_session_expires_at <= $2)
returning id, event_id, user_id, status, expires_at, waitlist_pos, stripe_checkout_session_id, stripe_checkout_session_url, stripe_session_expires_at, stripe_payment_intent_id, paid_at, created_at, updated_at
`

type ExpireOverduePendingForEventParams struct {
	EventID uuid.UUID
	Now     *time.Time
}

func (q *Queries) ExpireOverduePendingForEvent(ctx context.Context, arg ExpireOverduePendingForEventParams) ([]Registration, error) {
	rows, err := q.db.Query(ctx, expireOverduePendingForEvent, arg.EventID, arg.Now)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Registration
	for rows.Next() {
		var i Registration
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.UserID,
			&i.Status,
			&i.ExpiresAt,
			&i.WaitlistPos,
			&i.StripeCheckoutSessionID,
			&i.StripeCheckoutSessionUrl,
			&i.StripeSessionExpiresAt,
			&i.StripePaymentIntentID,
			&i.PaidAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getActiveRegistration = `-- name: GetActiveRegistration :one
select id, event_id, user_id, status, expires_at, waitlist_pos, stripe_checkout_session_id, stripe_checkout_session_url, stripe_session_expires_at, stripe_payment_intent_id, paid_at, created_at, updated_at from registrations
where event_id = $1 and user_id = $2
    and status in ('pending_payment', 'paid', 'waitlisted', 'refund_requested')
`

type GetActiveRegistrationParams struct {
	EventID uuid.UUID
	UserID  uuid.UUID
}

func (q *Queries) GetActiveRegistration(ctx context.Context, arg GetActiveRegistrationParams) (Registration, error) {
	row := q.db.QueryRow(ctx, getActiveRegistration, arg.EventID, arg.UserID)
	var i Registration
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.UserID,
		&i.Status,
		&i.ExpiresAt,
		&i.WaitlistPos,
		&i.StripeCheckoutSessionID,
		&i.StripeCheckoutSessionUrl,
		&i.StripeSessionExpiresAt,
		&i.StripePaymentIntentID,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCubeChangeCubeID = `-- name: GetCubeChangeCubeID :one
select cube_id from cube_changes where id = $1
`

// SetCubes validation: which cube does a pinned change belong to?
func (q *Queries) GetCubeChangeCubeID(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getCubeChangeCubeID, id)
	var cube_id uuid.UUID
	err := row.Scan(&cube_id)
	return cube_id, err
}

const getEvent = `-- name: GetEvent :one
select id, organizer_id, name, description, location, starts_at, fee_cents, currency, max_participants, refund_deadline, status, waitlist_counter, created_at, updated_at from events where id = $1
`

func (q *Queries) GetEvent(ctx context.Context, id uuid.UUID) (Event, error) {
	row := q.db.QueryRow(ctx, getEvent, id)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.OrganizerID,
		&i.Name,
		&i.Description,
		&i.Location,
		&i.StartsAt,
		&i.FeeCents,
		&i.Currency,
		&i.MaxParticipants,
		&i.RefundDeadline,
		&i.Status,
		&i.WaitlistCounter,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEventCounts = `-- name: GetEventCounts :one
select count(*) filter (where status = 'paid')::int as paid_count,
    count(*) filter (where status = 'pending_payment')::int as pending_count,
    count(*) filter (where status = 'waitlisted')::int as waitlist_count
from registrations where event_id = $1
`

type GetEventCountsRow struct {
	PaidCount     int32
	PendingCount  int32
	WaitlistCount int32
}

func (q *Queries) GetEventCounts(ctx context.Context, eventID uuid.UUID) (GetEventCountsRow, error) {
	row := q.db.QueryRow(ctx, getEventCounts, eventID)
	var i GetEventCountsRow
	err := row.Scan(&i.PaidCount, &i.PendingCount, &i.WaitlistCount)
	return i, err
}

const getEventForUpdate = `-- name: GetEventForUpdate :one
select id, organizer_id, name, description, location, starts_at, fee_cents, currency, max_participants, refund_deadline, status, waitlist_counter, created_at, updated_at from events where id = $1 for update
`

func (q *Queries) GetEventForUpdate(ctx context.Context, id uuid.UUID) (Event, error) {
	row := q.db.QueryRow(ctx, getEventForUpdate, id)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.OrganizerID,
		&i.Name,
		&i.Description,
		&i.Location,
		&i.StartsAt,
		&i.FeeCents,
		&i.Currency,
		&i.MaxParticipants,
		&i.RefundDeadline,
		&i.Status,
		&i.WaitlistCounter,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRegistration = `-- name: GetRegistration :one
select id, event_id, user_id, status, expires_at, waitlist_pos, stripe_checkout_session_id, stripe_checkout_session_url, stripe_session_expires_at, stripe_payment_intent_id, paid_at, created_at, updated_at from registrations where id = $1
`

func (q *Queries) GetRegistration(ctx context.Context, id uuid.UUID) (Registration, error) {
	row := q.db.QueryRow(ctx, getRegistration, id)
	var i Registration
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.UserID,
		&i.Status,
		&i.ExpiresAt,
		&i.WaitlistPos,
		&i.StripeCheckoutSessionID,
		&i.StripeCheckoutSessionUrl,
		&i.StripeSessionExpiresAt,
		&i.StripePaymentIntentID,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRegistrationByCheckoutSession = `-- name: GetRegistrationByCheckoutSession :one
select id, event_id, user_id, status, expires_at, waitlist_pos, stripe_checkout_session_id, stripe_checkout_session_url, stripe_session_expires_at, stripe_payment_intent_id, paid_at, created_at, updated_at from registrations
where stripe_checkout_session_id = $1
`

func (q *Queries) GetRegistrationByCheckoutSession(ctx context.Context, sessionID *string) (Registration, error) {
	row := q.db.QueryRow(ctx, getRegistrationByCheckoutSession, sessionID)
	var i Registration
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.UserID,
		&i.Status,
		&i.ExpiresAt,
		&i.WaitlistPos,
		&i.StripeCheckoutSessionID,
		&i.StripeCheckoutSessionUrl,
		&i.StripeSessionExpiresAt,
		&i.StripePaymentIntentID,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRegistrationByPaymentIntent = `-- name: GetRegistrationByPaymentIntent :one
select id, event_id, user_id, status, expires_at, waitlist_pos, stripe_checkout_session_id, stripe_checkout_session_url, stripe_session_expires_at, stripe_payment_intent_id, paid_at, created_at, updated_at from registrations
where stripe_payment_intent_id = $1
`

// charge.refunded arrives with a payment intent, not a session id.
func (q *Queries) GetRegistrationByPaymentIntent(ctx context.Context, paymentIntentID *string) (Registration, error) {
	row := q.db.QueryRow(ctx, getRegistrationByPaymentIntent, paymentIntentID)
	var i Registration
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.UserID,
		&i.Status,
		&i.ExpiresAt,
		&i.WaitlistPos,
		&i.StripeCheckoutSessionID,
		&i.StripeCheckoutSessionUrl,
		&i.StripeSessionExpiresAt,
		&i.StripePaymentIntentID,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const incrementWaitlistCounter = `-- name: IncrementWaitlistCounter :one
update events set waitlist_counter = waitlist_counter + 1
where id = $1
returning waitlist_counter
`

func (q *Queries) IncrementWaitlistCounter(ctx context.Context, id uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, incrementWaitlistCounter, id)
	var waitlist_counter int64
	err := row.Scan(&waitlist_counter)
	return waitlist_counter, err
}

const insertEventCube = `-- name: InsertEventCube :exec
insert into event_cubes (event_id, cube_id, cube_change_id)
values ($1, $2, $3)
`

type InsertEventCubeParams struct {
	EventID      uuid.UUID
	CubeID       uuid.UUID
	CubeChangeID pgtype.UUID
}

func (q *Queries) InsertEventCube(ctx context.Context, arg InsertEventCubeParams) error {
	_, err := q.db.Exec(ctx, insertEventCube, arg.EventID, arg.CubeID, arg.CubeChangeID)
	return err
}

const insertStripeEvent = `-- name: InsertStripeEvent :execrows
insert into stripe_events (stripe_event_id, type)
values ($1, $2)
on conflict do nothing
`

type InsertStripeEventParams struct {
	StripeEventID string
	Type          string
}

func (q *Queries) InsertStripeEvent(ctx context.Context, arg InsertStripeEventParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertStripeEvent, arg.StripeEventID, arg.Type)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listActiveRegistrationsForEvent = `-- name: ListActiveRegistrationsForEvent :many
select r.id, r.event_id, r.user_id, r.status, r.expires_at, r.waitlist_pos, r.stripe_checkout_session_id, r.stripe_checkout_session_url, r.stripe_session_expires_at, r.stripe_payment_intent_id, r.paid_at, r.created_at, r.updated_at, u.display_name, u.email from registrations r
join users u on u.id = r.user_id
where r.event_id = $1
    and r.status in ('pending_payment', 'paid', 'waitlisted', 'refund_requested')
order by r.created_at
`

type ListActiveRegistrationsForEventRow struct {
	ID                       uuid.UUID
	EventID                  uuid.UUID
	UserID                   uuid.UUID
	Status                   string
	ExpiresAt                *time.Time
	WaitlistPos              *int64
	StripeCheckoutSessionID  *string
	StripeCheckoutSessionUrl *string
	StripeSessionExpiresAt   *time.Time
	StripePaymentIntentID    *string
	PaidAt                   *time.Time
	CreatedAt                time.Time
	UpdatedAt                time.Time
	DisplayName              string
	Email                    string
}

// Event cancel: everything that needs a transition or refund.
func (q *Queries) ListActiveRegistrationsForEvent(ctx context.Context, eventID uuid.UUID) ([]ListActiveRegistrationsForEventRow, error) {
	rows, err := q.db.Query(ctx, listActiveRegistrationsForEvent, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveRegistrationsForEventRow
	for rows.Next() {
		var i ListActiveRegistrationsForEventRow
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.UserID,
			&i.Status,
			&i.ExpiresAt,
			&i.WaitlistPos,
			&i.StripeCheckoutSessionID,
			&i.StripeCheckoutSessionUrl,
			&i.StripeSessionExpiresAt,
			&i.StripePaymentIntentID,
			&i.PaidAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DisplayName,
			&i.Email,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventCubes = `-- name: ListEventCubes :many
select ec.cube_id, ec.cube_change_id, cu.name as cube_name,
    ch.version as pinned_version, ch.created_at as pinned_at
from event_cubes ec
join cubes cu on cu.id = ec.cube_id
left join cube_changes ch on ch.id = ec.cube_change_id
where ec.event_id = $1
order by cu.name
`

type ListEventCubesRow struct {
	CubeID        uuid.UUID
	CubeChangeID  pgtype.UUID
	CubeName      string
	PinnedVersion *int32
	PinnedAt      *time.Time
}

func (q *Queries) ListEventCubes(ctx context.Context, eventID uuid.UUID) ([]ListEventCubesRow, error) {
	rows, err := q.db.Query(ctx, listEventCubes, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEventCubesRow
	for rows.Next() {
		var i ListEventCubesRow
		if err := rows.Scan(
			&i.CubeID,
			&i.CubeChangeID,
			&i.CubeName,
			&i.PinnedVersion,
			&i.PinnedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventIDsWithOverduePending = `-- name: ListEventIDsWithOverduePending :many
select distinct event_id from registrations
where status = 'pending_payment' and expires_at <= $1
    and (stripe_session_expires_at is null or stripe_session_expires_at <= $1)
`

// Sweeper scan: which events have overdue pending rows (skipping rows
// whose Checkout session is still live — the webhook owns those).
func (q *Queries) ListEventIDsWithOverduePending(ctx context.Context, now *time.Time) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listEventIDsWithOverduePending, now)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var event_id uuid.UUID
		if err := rows.Scan(&event_id); err != nil {
			return nil, err
		}
		items = append(items, event_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventRegistrations = `-- name: ListEventRegistrations :many
select r.id, r.event_id, r.user_id, r.status, r.expires_at, r.waitlist_pos, r.stripe_checkout_session_id, r.stripe_checkout_session_url, r.stripe_session_expires_at, r.stripe_payment_intent_id, r.paid_at, r.created_at, r.updated_at, u.display_name, u.email from registrations r
join users u on u.id = r.user_id
where r.event_id = $1
order by r.created_at
`

type ListEventRegistrationsRow struct {
	ID                       uuid.UUID
	EventID                  uuid.UUID
	UserID                   uuid.UUID
	Status                   string
	ExpiresAt                *time.Time
	WaitlistPos              *int64
	StripeCheckoutSessionID  *string
	StripeCheckoutSessionUrl *string
	StripeSessionExpiresAt   *time.Time
	StripePaymentIntentID    *string
	PaidAt                   *time.Time
	CreatedAt                time.Time
	UpdatedAt                time.Time
	DisplayName              string
	Email                    string
}

// Organizer panel: every row with user identity.
func (q *Queries) ListEventRegistrations(ctx context.Context, eventID uuid.UUID) ([]ListEventRegistrationsRow, error) {
	rows, err := q.db.Query(ctx, listEventRegistrations, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEventRegistrationsRow
	for rows.Next() {
		var i ListEventRegistrationsRow
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.UserID,
			&i.Status,
			&i.ExpiresAt,
			&i.WaitlistPos,
			&i.StripeCheckoutSessionID,
			&i.StripeCheckoutSessionUrl,
			&i.StripeSessionExpiresAt,
			&i.StripePaymentIntentID,
			&i.PaidAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DisplayName,
			&i.Email,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEvents = `-- name: ListEvents :many
select e.id, e.organizer_id, e.name, e.description, e.location, e.starts_at, e.fee_cents, e.currency, e.max_participants, e.refund_deadline, e.status, e.waitlist_counter, e.created_at, e.updated_at,
    coalesce(c.paid, 0)::int as paid_count,
    coalesce(c.pending, 0)::int as pending_count,
    coalesce(c.waitlisted, 0)::int as waitlist_count,
    my.status as my_status
from events e
left join lateral (
    select count(*) filter (where r.status = 'paid') as paid,
        count(*) filter (where r.status = 'pending_payment') as pending,
        count(*) filter (where r.status = 'waitlisted') as waitlisted
    from registrations r where r.event_id = e.id
) c on true
left join registrations my on my.event_id = e.id
    and my.user_id = $1
    and my.status in ('pending_payment', 'paid', 'waitlisted', 'refund_requested')
where e.status <> 'draft' or $2::bool
order by (case when e.status in ('draft', 'published', 'started') then 0 else 1 end),
    (case when e.status in ('draft', 'published', 'started') then e.starts_at end) asc,
    e.starts_at desc
`

type ListEventsParams struct {
	UserID        uuid.UUID
	IncludeDrafts bool
}

type ListEventsRow struct {
	ID              uuid.UUID
	OrganizerID     uuid.UUID
	Name            string
	Description     string
	Location        string
	StartsAt        time.Time
	FeeCents        int32
	Currency        string
	MaxParticipants int32
	RefundDeadline  *time.Time
	Status          string
	WaitlistCounter int64
	CreatedAt       time.Time
	UpdatedAt       time.Time
	PaidCount       int32
	PendingCount    int32
	WaitlistCount   int32
	MyStatus        *string
}

// Active events (published/started) first by soonest start; then past
// (finished/cancelled) newest first. Drafts only when include_drafts
// (admin). my_status = the caller's active registration, if any.
func (q *Queries) ListEvents(ctx context.Context, arg ListEventsParams) ([]ListEventsRow, error) {
	rows, err := q.db.Query(ctx, listEvents, arg.UserID, arg.IncludeDrafts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEventsRow
	for rows.Next() {
		var i ListEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizerID,
			&i.Name,
			&i.Description,
			&i.Location,
			&i.StartsAt,
			&i.FeeCents,
			&i.Currency,
			&i.MaxParticipants,
			&i.RefundDeadline,
			&i.Status,
			&i.WaitlistCounter,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PaidCount,
			&i.PendingCount,
			&i.WaitlistCount,
			&i.MyStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPaidAttendees = `-- name: ListPaidAttendees :many
select u.display_name from registrations r
join users u on u.id = r.user_id
where r.event_id = $1 and r.status = 'paid'
order by r.paid_at
`

func (q *Queries) ListPaidAttendees(ctx context.Context, eventID uuid.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listPaidAttendees, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var display_name string
		if err := rows.Scan(&display_name); err != nil {
			return nil, err
		}
		items = append(items, display_name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markRegistrationPaid = `-- name: MarkRegistrationPaid :one
update registrations set status = 'paid', paid_at = $1,
    stripe_payment_intent_id = coalesce($2, stripe_payment_intent_id),
    expires_at = null, waitlist_pos = null, updated_at = now()
where id = $3
returning id, event_id, user_id, status, expires_at, waitlist_pos, stripe_checkout_session_id, stripe_checkout_session_url, stripe_session_expires_at, stripe_payment_intent_id, paid_at, created_at, updated_at
`

type MarkRegistrationPaidParams struct {
	PaidAt          *time.Time
	PaymentIntentID *string
	ID              uuid.UUID
}

func (q *Queries) MarkRegistrationPaid(ctx context.Context, arg MarkRegistrationPaidParams) (Registration, error) {
	row := q.db.QueryRow(ctx, markRegistrationPaid, arg.PaidAt, arg.PaymentIntentID, arg.ID)
	var i Registration
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.UserID,
		&i.Status,
		&i.ExpiresAt,
		&i.WaitlistPos,
		&i.StripeCheckoutSessionID,
		&i.StripeCheckoutSessionUrl,
		&i.StripeSessionExpiresAt,
		&i.StripePaymentIntentID,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const nextWaitlisted = `-- name: NextWaitlisted :one
select id, event_id, user_id, status, expires_at, waitlist_pos, stripe_checkout_session_id, stripe_checkout_session_url, stripe_session_expires_at, stripe_payment_intent_id, paid_at, created_at, updated_at from registrations
where event_id = $1 and status = 'waitlisted'
order by waitlist_pos
limit 1
`

func (q *Queries) NextWaitlisted(ctx context.Context, eventID uuid.UUID) (Registration, error) {
	row := q.db.QueryRow(ctx, nextWaitlisted, eventID)
	var i Registration
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.UserID,
		&i.Status,
		&i.ExpiresAt,
		&i.WaitlistPos,
		&i.StripeCheckoutSessionID,
		&i.StripeCheckoutSessionUrl,
		&i.StripeSessionExpiresAt,
		&i.StripePaymentIntentID,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const promoteToPendingPayment = `-- name: PromoteToPendingPayment :one
update registrations set status = 'pending_payment',
    expires_at = $1, waitlist_pos = null, updated_at = now()
where id = $2
returning id, event_id, user_id, status, expires_at, waitlist_pos, stripe_checkout_session_id, stripe_checkout_session_url, stripe_session_expires_at, stripe_payment_intent_id, paid_at, created_at, updated_at
`

type PromoteToPendingPaymentParams struct {
	ExpiresAt *time.Time
	ID        uuid.UUID
}

func (q *Queries) PromoteToPendingPayment(ctx context.Context, arg PromoteToPendingPaymentParams) (Registration, error) {
	row := q.db.QueryRow(ctx, promoteToPendingPayment, arg.ExpiresAt, arg.ID)
	var i Registration
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.UserID,
		&i.Status,
		&i.ExpiresAt,
		&i.WaitlistPos,
		&i.StripeCheckoutSessionID,
		&i.StripeCheckoutSessionUrl,
		&i.StripeSessionExpiresAt,
		&i.StripePaymentIntentID,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setEventStatus = `-- name: SetEventStatus :one
update events set status = $1, updated_at = now()
where id = $2
returning id, organizer_id, name, description, location, starts_at, fee_cents, currency, max_participants, refund_deadline, status, waitlist_counter, created_at, updated_at
`

type SetEventStatusParams struct {
	Status string
	ID     uuid.UUID
}

func (q *Queries) SetEventStatus(ctx context.Context, arg SetEventStatusParams) (Event, error) {
	row := q.db.QueryRow(ctx, setEventStatus, arg.Status, arg.ID)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.OrganizerID,
		&i.Name,
		&i.Description,
		&i.Location,
		&i.StartsAt,
		&i.FeeCents,
		&i.Currency,
		&i.MaxParticipants,
		&i.RefundDeadline,
		&i.Status,
		&i.WaitlistCounter,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setRegistrationCheckoutSession = `-- name: SetRegistrationCheckoutSession :exec
update registrations set
    stripe_checkout_session_id = $1,
    stripe_checkout_session_url = $2,
    stripe_session_expires_at = $3,
    updated_at = now()
where id = $4
`

type SetRegistrationCheckoutSessionParams struct {
	SessionID        *string
	SessionUrl       *string
	SessionExpiresAt *time.Time
	ID               uuid.UUID
}

func (q *Queries) SetRegistrationCheckoutSession(ctx context.Context, arg SetRegistrationCheckoutSessionParams) error {
	_, err := q.db.Exec(
		ctx, setRegistrationCheckoutSession,
		arg.SessionID,
		arg.SessionUrl,
		arg.SessionExpiresAt,
		arg.ID,
	)
	return err
}

const setRegistrationPaymentIntent = `-- name: SetRegistrationPaymentIntent :exec
update registrations set stripe_payment_intent_id = $1,
    updated_at = now()
where id = $2
`

type SetRegistrationPaymentIntentParams struct {
	PaymentIntentID *string
	ID              uuid.UUID
}

func (q *Queries) SetRegistrationPaymentIntent(ctx context.Context, arg SetRegistrationPaymentIntentParams) error {
	_, err := q.db.Exec(ctx, setRegistrationPaymentIntent, arg.PaymentIntentID, arg.ID)
	return err
}

const setRegistrationTerminal = `-- name: SetRegistrationTerminal :one
update registrations set status = $1,
    expires_at = null, waitlist_pos = null, updated_at = now()
where id = $2
returning id, event_id, user_id, status, expires_at, waitlist_pos, stripe_checkout_session_id, stripe_checkout_session_url, stripe_session_expires_at, stripe_payment_intent_id, paid_at, created_at, updated_at
`

type SetRegistrationTerminalParams struct {
	Status string
	ID     uuid.UUID
}

// All transitions into cancelled / refund_requested / refunded / expired:
// the row leaves the capacity/waitlist domain, so both columns null out.
func (q *Queries) SetRegistrationTerminal(ctx context.Context, arg SetRegistrationTerminalParams) (Registration, error) {
	row := q.db.QueryRow(ctx, setRegistrationTerminal, arg.Status, arg.ID)
	var i Registration
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.UserID,
		&i.Status,
		&i.ExpiresAt,
		&i.WaitlistPos,
		&i.StripeCheckoutSessionID,
		&i.StripeCheckoutSessionUrl,
		&i.StripeSessionExpiresAt,
		&i.StripePaymentIntentID,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateEventMeta = `-- name: UpdateEventMeta :one
update events set
    name = coalesce($1, name),
    description = coalesce($2, description),
    location = coalesce($3, location),
    starts_at = coalesce($4, starts_at),
    fee_cents = coalesce($5, fee_cents),
    currency = coalesce($6, currency),
    max_participants = coalesce($7, max_participants),
    refund_deadline = coalesce($8, refund_deadline),
    updated_at = now()
where id = $9
returning id, organizer_id, name, description, location, starts_at, fee_cents, currency, max_participants, refund_deadline, status, waitlist_counter, created_at, updated_at
`

type UpdateEventMetaParams struct {
	Name            *string
	Description     *string
	Location        *string
	StartsAt        *time.Time
	FeeCents        *int32
	Currency        *string
	MaxParticipants *int32
	RefundDeadline  *time.Time
	ID              uuid.UUID
}

// PATCH semantics: omitted field = unchanged. Clearing refund_deadline to
// null is not supported (YAGNI, spec §3 locks most fields post-publish).
func (q *Queries) UpdateEventMeta(ctx context.Context, arg UpdateEventMetaParams) (Event, error) {
	row := q.db.QueryRow(
		ctx, updateEventMeta,
		arg.Name,
		arg.Description,
		arg.Location,
		arg.StartsAt,
		arg.FeeCents,
		arg.Currency,
		arg.MaxParticipants,
		arg.RefundDeadline,
		arg.ID,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.OrganizerID,
		&i.Name,
		&i.Description,
		&i.Location,
		&i.StartsAt,
		&i.FeeCents,
		&i.Currency,
		&i.MaxParticipants,
		&i.RefundDeadline,
		&i.Status,
		&i.WaitlistCounter,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
