// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AuthToken struct {
	TokenHash []byte
	UserID    uuid.UUID
	Purpose   string
	CreatedAt time.Time
	ExpiresAt time.Time
}

type Card struct {
	ScryfallID      uuid.UUID
	OracleID        uuid.UUID
	Name            string
	NormalizedName  string
	ReleasedAt      time.Time
	SetCode         string
	SetName         string
	CollectorNumber string
	Rarity          string
	Layout          string
	ManaCost        string
	Cmc             float64
	TypeLine        string
	OracleText      string
	Colors          []string
	ColorIdentity   []string
	Promo           bool
	ImageSmall      *string
	ImageNormal     *string
	BackImageSmall  *string
	BackImageNormal *string
	UpdatedAt       time.Time
}

type CardSyncRun struct {
	ID            int64
	StartedAt     time.Time
	FinishedAt    *time.Time
	Status        string
	BulkUpdatedAt *time.Time
	CardsCount    *int32
	Error         *string
}

type CardsStaging struct {
	ScryfallID      uuid.UUID
	OracleID        uuid.UUID
	Name            string
	NormalizedName  string
	ReleasedAt      time.Time
	SetCode         string
	SetName         string
	CollectorNumber string
	Rarity          string
	Layout          string
	ManaCost        string
	Cmc             float64
	TypeLine        string
	OracleText      string
	Colors          []string
	ColorIdentity   []string
	Promo           bool
	ImageSmall      *string
	ImageNormal     *string
	BackImageSmall  *string
	BackImageNormal *string
}

type CollectionItem struct {
	UserID     uuid.UUID
	ScryfallID uuid.UUID
	OracleID   uuid.UUID
	Quantity   int32
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type Cube struct {
	ID          uuid.UUID
	OwnerID     uuid.UUID
	Name        string
	Description string
	Visibility  string
	Version     int32
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type CubeCard struct {
	CubeID     uuid.UUID
	OracleID   uuid.UUID
	ScryfallID uuid.UUID
	Quantity   int32
	AddedAt    time.Time
}

type CubeChange struct {
	ID        uuid.UUID
	CubeID    uuid.UUID
	Version   int32
	AuthorID  uuid.UUID
	Note      string
	CreatedAt time.Time
}

type CubeChangeItem struct {
	ChangeID   uuid.UUID
	Kind       string
	OracleID   uuid.UUID
	ScryfallID uuid.UUID
	Quantity   int32
}

type Event struct {
	ID              uuid.UUID
	OrganizerID     uuid.UUID
	Name            string
	Description     string
	Location        string
	StartsAt        time.Time
	FeeCents        int32
	Currency        string
	MaxParticipants int32
	RefundDeadline  *time.Time
	Status          string
	WaitlistCounter int64
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type EventCube struct {
	EventID      uuid.UUID
	CubeID       uuid.UUID
	CubeChangeID pgtype.UUID
}

type OauthIdentity struct {
	Provider       string
	ProviderUserID string
	UserID         uuid.UUID
	CreatedAt      time.Time
}

type Registration struct {
	ID                       uuid.UUID
	EventID                  uuid.UUID
	UserID                   uuid.UUID
	Status                   string
	ExpiresAt                *time.Time
	WaitlistPos              *int64
	StripeCheckoutSessionID  *string
	StripeCheckoutSessionUrl *string
	StripeSessionExpiresAt   *time.Time
	StripePaymentIntentID    *string
	PaidAt                   *time.Time
	CreatedAt                time.Time
	UpdatedAt                time.Time
}

type Session struct {
	TokenHash []byte
	UserID    uuid.UUID
	CreatedAt time.Time
	ExpiresAt time.Time
}

type StripeEvent struct {
	StripeEventID string
	Type          string
	ReceivedAt    time.Time
}

type User struct {
	ID              uuid.UUID
	Email           string
	DisplayName     string
	PasswordHash    *string
	EmailVerifiedAt *time.Time
	CreatedAt       time.Time
	Role            string
}
