// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"

	"github.com/google/uuid"
)

type AuthToken struct {
	TokenHash []byte
	UserID    uuid.UUID
	Purpose   string
	CreatedAt time.Time
	ExpiresAt time.Time
}

type OauthIdentity struct {
	Provider       string
	ProviderUserID string
	UserID         uuid.UUID
	CreatedAt      time.Time
}

type Session struct {
	TokenHash []byte
	UserID    uuid.UUID
	CreatedAt time.Time
	ExpiresAt time.Time
}

type User struct {
	ID              uuid.UUID
	Email           string
	DisplayName     string
	PasswordHash    *string
	EmailVerifiedAt *time.Time
	CreatedAt       time.Time
}
