// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tournaments.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countOpenRoundsForEvent = `-- name: CountOpenRoundsForEvent :one
select count(*) from rounds r
join tournaments t on t.id = r.tournament_id
where t.event_id = $1 and r.status <> 'completed'
`

// Finish guard (spec §3.2): events.Transition("finish") refuses while
// any round is not completed.
func (q *Queries) CountOpenRoundsForEvent(ctx context.Context, eventID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countOpenRoundsForEvent, eventID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createRound = `-- name: CreateRound :one
insert into rounds (tournament_id, number, seed)
values ($1, $2, $3)
returning id, tournament_id, number, status, seed, published_at, completed_at, created_at, updated_at
`

type CreateRoundParams struct {
	TournamentID uuid.UUID
	Number       int32
	Seed         int64
}

func (q *Queries) CreateRound(ctx context.Context, arg CreateRoundParams) (Round, error) {
	row := q.db.QueryRow(ctx, createRound, arg.TournamentID, arg.Number, arg.Seed)
	var i Round
	err := row.Scan(
		&i.ID,
		&i.TournamentID,
		&i.Number,
		&i.Status,
		&i.Seed,
		&i.PublishedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTournament = `-- name: CreateTournament :one
insert into tournaments (event_id, planned_rounds)
values ($1, $2)
returning id, event_id, planned_rounds, created_at, updated_at
`

type CreateTournamentParams struct {
	EventID       uuid.UUID
	PlannedRounds int32
}

func (q *Queries) CreateTournament(ctx context.Context, arg CreateTournamentParams) (Tournament, error) {
	row := q.db.QueryRow(ctx, createTournament, arg.EventID, arg.PlannedRounds)
	var i Tournament
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.PlannedRounds,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteMatchesForRound = `-- name: DeleteMatchesForRound :exec
delete from matches where round_id = $1
`

func (q *Queries) DeleteMatchesForRound(ctx context.Context, roundID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteMatchesForRound, roundID)
	return err
}

const dropTournamentPlayerByEventUser = `-- name: DropTournamentPlayerByEventUser :execrows
update tournament_players tp
set dropped_at = $1
from tournaments t
where tp.tournament_id = t.id
  and t.event_id = $2
  and tp.user_id = $3
  and tp.dropped_at is null
`

type DropTournamentPlayerByEventUserParams struct {
	DroppedAt *time.Time
	EventID   uuid.UUID
	UserID    uuid.UUID
}

// Removing a participant after the event starts must also take them out of
// the pairings: tournament_players is snapshotted at start and nothing else
// writes it, so the roster would otherwise keep pairing a removed player.
// Dropping (rather than deleting) is what the organizer's own Drop button
// does, so results already played stay on the books. A no-op when the event
// has no tournament or the player is already dropped.
func (q *Queries) DropTournamentPlayerByEventUser(ctx context.Context, arg DropTournamentPlayerByEventUserParams) (int64, error) {
	result, err := q.db.Exec(ctx, dropTournamentPlayerByEventUser, arg.DroppedAt, arg.EventID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getMatch = `-- name: GetMatch :one
select m.id, m.round_id, m.table_number, m.player1_id, m.player2_id, m.p1_games, m.p2_games, m.draws, m.reported_by, m.reported_at, m.created_at, m.updated_at, r.number as round_number, r.status as round_status,
    r.tournament_id
from matches m
join rounds r on r.id = m.round_id
where m.id = $1
`

type GetMatchRow struct {
	ID           uuid.UUID
	RoundID      uuid.UUID
	TableNumber  int32
	Player1ID    uuid.UUID
	Player2ID    pgtype.UUID
	P1Games      *int32
	P2Games      *int32
	Draws        *int32
	ReportedBy   pgtype.UUID
	ReportedAt   *time.Time
	CreatedAt    time.Time
	UpdatedAt    time.Time
	RoundNumber  int32
	RoundStatus  string
	TournamentID uuid.UUID
}

func (q *Queries) GetMatch(ctx context.Context, id uuid.UUID) (GetMatchRow, error) {
	row := q.db.QueryRow(ctx, getMatch, id)
	var i GetMatchRow
	err := row.Scan(
		&i.ID,
		&i.RoundID,
		&i.TableNumber,
		&i.Player1ID,
		&i.Player2ID,
		&i.P1Games,
		&i.P2Games,
		&i.Draws,
		&i.ReportedBy,
		&i.ReportedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RoundNumber,
		&i.RoundStatus,
		&i.TournamentID,
	)
	return i, err
}

const getRoundByNumber = `-- name: GetRoundByNumber :one
select id, tournament_id, number, status, seed, published_at, completed_at, created_at, updated_at from rounds
where tournament_id = $1
    and number = $2
`

type GetRoundByNumberParams struct {
	TournamentID uuid.UUID
	Number       int32
}

func (q *Queries) GetRoundByNumber(ctx context.Context, arg GetRoundByNumberParams) (Round, error) {
	row := q.db.QueryRow(ctx, getRoundByNumber, arg.TournamentID, arg.Number)
	var i Round
	err := row.Scan(
		&i.ID,
		&i.TournamentID,
		&i.Number,
		&i.Status,
		&i.Seed,
		&i.PublishedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTournamentByEvent = `-- name: GetTournamentByEvent :one
select id, event_id, planned_rounds, created_at, updated_at from tournaments where event_id = $1
`

func (q *Queries) GetTournamentByEvent(ctx context.Context, eventID uuid.UUID) (Tournament, error) {
	row := q.db.QueryRow(ctx, getTournamentByEvent, eventID)
	var i Tournament
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.PlannedRounds,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTournamentByEventForUpdate = `-- name: GetTournamentByEventForUpdate :one
select id, event_id, planned_rounds, created_at, updated_at from tournaments where event_id = $1 for update
`

// Mutations lock the tournament row: one round in flight, no racing
// pair/publish/complete/report.
func (q *Queries) GetTournamentByEventForUpdate(ctx context.Context, eventID uuid.UUID) (Tournament, error) {
	row := q.db.QueryRow(ctx, getTournamentByEventForUpdate, eventID)
	var i Tournament
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.PlannedRounds,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTournamentPlayer = `-- name: GetTournamentPlayer :one
select tp.id, tp.tournament_id, tp.user_id, tp.dropped_at, u.display_name
from tournament_players tp
join users u on u.id = tp.user_id
where tp.id = $1
`

type GetTournamentPlayerRow struct {
	ID           uuid.UUID
	TournamentID uuid.UUID
	UserID       uuid.UUID
	DroppedAt    *time.Time
	DisplayName  string
}

func (q *Queries) GetTournamentPlayer(ctx context.Context, id uuid.UUID) (GetTournamentPlayerRow, error) {
	row := q.db.QueryRow(ctx, getTournamentPlayer, id)
	var i GetTournamentPlayerRow
	err := row.Scan(
		&i.ID,
		&i.TournamentID,
		&i.UserID,
		&i.DroppedAt,
		&i.DisplayName,
	)
	return i, err
}

const insertMatch = `-- name: InsertMatch :one
insert into matches (round_id, table_number, player1_id, player2_id,
    p1_games, p2_games, draws, reported_at)
values ($1, $2, $3,
    $4, $5, $6,
    $7, $8)
returning id, round_id, table_number, player1_id, player2_id, p1_games, p2_games, draws, reported_by, reported_at, created_at, updated_at
`

type InsertMatchParams struct {
	RoundID     uuid.UUID
	TableNumber int32
	Player1ID   uuid.UUID
	Player2ID   pgtype.UUID
	P1Games     *int32
	P2Games     *int32
	Draws       *int32
	ReportedAt  *time.Time
}

func (q *Queries) InsertMatch(ctx context.Context, arg InsertMatchParams) (Match, error) {
	row := q.db.QueryRow(
		ctx, insertMatch,
		arg.RoundID,
		arg.TableNumber,
		arg.Player1ID,
		arg.Player2ID,
		arg.P1Games,
		arg.P2Games,
		arg.Draws,
		arg.ReportedAt,
	)
	var i Match
	err := row.Scan(
		&i.ID,
		&i.RoundID,
		&i.TableNumber,
		&i.Player1ID,
		&i.Player2ID,
		&i.P1Games,
		&i.P2Games,
		&i.Draws,
		&i.ReportedBy,
		&i.ReportedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertMatchResultReport = `-- name: InsertMatchResultReport :one
insert into match_result_reports (
    match_id, reported_by, is_organizer, p1_games, p2_games)
values (
    $1, $2, $3,
    $4, $5)
returning id, match_id, reported_by, is_organizer, p1_games, p2_games, reported_at
`

type InsertMatchResultReportParams struct {
	MatchID     uuid.UUID
	ReportedBy  uuid.UUID
	IsOrganizer bool
	P1Games     int32
	P2Games     int32
}

func (q *Queries) InsertMatchResultReport(ctx context.Context, arg InsertMatchResultReportParams) (MatchResultReport, error) {
	row := q.db.QueryRow(
		ctx, insertMatchResultReport,
		arg.MatchID,
		arg.ReportedBy,
		arg.IsOrganizer,
		arg.P1Games,
		arg.P2Games,
	)
	var i MatchResultReport
	err := row.Scan(
		&i.ID,
		&i.MatchID,
		&i.ReportedBy,
		&i.IsOrganizer,
		&i.P1Games,
		&i.P2Games,
		&i.ReportedAt,
	)
	return i, err
}

const insertTournamentPlayer = `-- name: InsertTournamentPlayer :one
insert into tournament_players (tournament_id, user_id)
values ($1, $2)
returning id, tournament_id, user_id, dropped_at, created_at
`

type InsertTournamentPlayerParams struct {
	TournamentID uuid.UUID
	UserID       uuid.UUID
}

func (q *Queries) InsertTournamentPlayer(ctx context.Context, arg InsertTournamentPlayerParams) (TournamentPlayer, error) {
	row := q.db.QueryRow(ctx, insertTournamentPlayer, arg.TournamentID, arg.UserID)
	var i TournamentPlayer
	err := row.Scan(
		&i.ID,
		&i.TournamentID,
		&i.UserID,
		&i.DroppedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listMatchResultReportsForTournament = `-- name: ListMatchResultReportsForTournament :many
select rr.id, rr.match_id, rr.reported_by, rr.is_organizer, rr.p1_games, rr.p2_games, rr.reported_at, u.display_name
from match_result_reports rr
join matches mt on mt.id = rr.match_id
join rounds rd on rd.id = mt.round_id
join users u on u.id = rr.reported_by
where rd.tournament_id = $1
order by rr.match_id, rr.reported_at, rr.id
`

type ListMatchResultReportsForTournamentRow struct {
	ID          uuid.UUID
	MatchID     uuid.UUID
	ReportedBy  uuid.UUID
	IsOrganizer bool
	P1Games     int32
	P2Games     int32
	ReportedAt  time.Time
	DisplayName string
}

// Every report for one tournament, oldest first, with the reporter's name
// for the organizer's dispute history.
// rr.id breaks ties: reported_at is transaction-start time in Postgres, so
// two reports can share a timestamp, and "latest wins" must stay stable.
func (q *Queries) ListMatchResultReportsForTournament(ctx context.Context, tournamentID uuid.UUID) ([]ListMatchResultReportsForTournamentRow, error) {
	rows, err := q.db.Query(ctx, listMatchResultReportsForTournament, tournamentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMatchResultReportsForTournamentRow
	for rows.Next() {
		var i ListMatchResultReportsForTournamentRow
		if err := rows.Scan(
			&i.ID,
			&i.MatchID,
			&i.ReportedBy,
			&i.IsOrganizer,
			&i.P1Games,
			&i.P2Games,
			&i.ReportedAt,
			&i.DisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMatchesForRound = `-- name: ListMatchesForRound :many
select id, round_id, table_number, player1_id, player2_id, p1_games, p2_games, draws, reported_by, reported_at, created_at, updated_at from matches
where round_id = $1
order by table_number
`

func (q *Queries) ListMatchesForRound(ctx context.Context, roundID uuid.UUID) ([]Match, error) {
	rows, err := q.db.Query(ctx, listMatchesForRound, roundID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Match
	for rows.Next() {
		var i Match
		if err := rows.Scan(
			&i.ID,
			&i.RoundID,
			&i.TableNumber,
			&i.Player1ID,
			&i.Player2ID,
			&i.P1Games,
			&i.P2Games,
			&i.Draws,
			&i.ReportedBy,
			&i.ReportedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMatchesForTournament = `-- name: ListMatchesForTournament :many
select m.id, m.round_id, m.table_number, m.player1_id, m.player2_id, m.p1_games, m.p2_games, m.draws, m.reported_by, m.reported_at, m.created_at, m.updated_at, r.number as round_number, r.status as round_status
from matches m
join rounds r on r.id = m.round_id
where r.tournament_id = $1
order by r.number, m.table_number
`

type ListMatchesForTournamentRow struct {
	ID          uuid.UUID
	RoundID     uuid.UUID
	TableNumber int32
	Player1ID   uuid.UUID
	Player2ID   pgtype.UUID
	P1Games     *int32
	P2Games     *int32
	Draws       *int32
	ReportedBy  pgtype.UUID
	ReportedAt  *time.Time
	CreatedAt   time.Time
	UpdatedAt   time.Time
	RoundNumber int32
	RoundStatus string
}

func (q *Queries) ListMatchesForTournament(ctx context.Context, tournamentID uuid.UUID) ([]ListMatchesForTournamentRow, error) {
	rows, err := q.db.Query(ctx, listMatchesForTournament, tournamentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMatchesForTournamentRow
	for rows.Next() {
		var i ListMatchesForTournamentRow
		if err := rows.Scan(
			&i.ID,
			&i.RoundID,
			&i.TableNumber,
			&i.Player1ID,
			&i.Player2ID,
			&i.P1Games,
			&i.P2Games,
			&i.Draws,
			&i.ReportedBy,
			&i.ReportedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RoundNumber,
			&i.RoundStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPaidRegistrationUsers = `-- name: ListPaidRegistrationUsers :many
select r.user_id, u.display_name
from registrations r
join users u on u.id = r.user_id
where r.event_id = $1 and r.status = 'paid'
order by u.display_name
`

type ListPaidRegistrationUsersRow struct {
	UserID      uuid.UUID
	DisplayName string
}

// Roster snapshot source (spec §3.1): paid registrations only.
func (q *Queries) ListPaidRegistrationUsers(ctx context.Context, eventID uuid.UUID) ([]ListPaidRegistrationUsersRow, error) {
	rows, err := q.db.Query(ctx, listPaidRegistrationUsers, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPaidRegistrationUsersRow
	for rows.Next() {
		var i ListPaidRegistrationUsersRow
		if err := rows.Scan(&i.UserID, &i.DisplayName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRounds = `-- name: ListRounds :many
select id, tournament_id, number, status, seed, published_at, completed_at, created_at, updated_at from rounds
where tournament_id = $1
order by number
`

func (q *Queries) ListRounds(ctx context.Context, tournamentID uuid.UUID) ([]Round, error) {
	rows, err := q.db.Query(ctx, listRounds, tournamentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Round
	for rows.Next() {
		var i Round
		if err := rows.Scan(
			&i.ID,
			&i.TournamentID,
			&i.Number,
			&i.Status,
			&i.Seed,
			&i.PublishedAt,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTournamentPlayers = `-- name: ListTournamentPlayers :many
select tp.id, tp.user_id, tp.dropped_at, u.display_name
from tournament_players tp
join users u on u.id = tp.user_id
where tp.tournament_id = $1
order by u.display_name
`

type ListTournamentPlayersRow struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	DroppedAt   *time.Time
	DisplayName string
}

func (q *Queries) ListTournamentPlayers(ctx context.Context, tournamentID uuid.UUID) ([]ListTournamentPlayersRow, error) {
	rows, err := q.db.Query(ctx, listTournamentPlayers, tournamentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTournamentPlayersRow
	for rows.Next() {
		var i ListTournamentPlayersRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.DroppedAt,
			&i.DisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const matchHasOrganizerReport = `-- name: MatchHasOrganizerReport :one
select exists (
    select 1 from match_result_reports
    where match_id = $1 and is_organizer
)
`

func (q *Queries) MatchHasOrganizerReport(ctx context.Context, matchID uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, matchHasOrganizerReport, matchID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const setMatchPlayers = `-- name: SetMatchPlayers :one
update matches set player1_id = $1,
    player2_id = $2, updated_at = now()
where id = $3
returning id, round_id, table_number, player1_id, player2_id, p1_games, p2_games, draws, reported_by, reported_at, created_at, updated_at
`

type SetMatchPlayersParams struct {
	Player1ID uuid.UUID
	Player2ID pgtype.UUID
	ID        uuid.UUID
}

func (q *Queries) SetMatchPlayers(ctx context.Context, arg SetMatchPlayersParams) (Match, error) {
	row := q.db.QueryRow(ctx, setMatchPlayers, arg.Player1ID, arg.Player2ID, arg.ID)
	var i Match
	err := row.Scan(
		&i.ID,
		&i.RoundID,
		&i.TableNumber,
		&i.Player1ID,
		&i.Player2ID,
		&i.P1Games,
		&i.P2Games,
		&i.Draws,
		&i.ReportedBy,
		&i.ReportedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setPlayerDropped = `-- name: SetPlayerDropped :one
update tournament_players set dropped_at = $1
where id = $2
returning id, tournament_id, user_id, dropped_at, created_at
`

type SetPlayerDroppedParams struct {
	DroppedAt *time.Time
	ID        uuid.UUID
}

func (q *Queries) SetPlayerDropped(ctx context.Context, arg SetPlayerDroppedParams) (TournamentPlayer, error) {
	row := q.db.QueryRow(ctx, setPlayerDropped, arg.DroppedAt, arg.ID)
	var i TournamentPlayer
	err := row.Scan(
		&i.ID,
		&i.TournamentID,
		&i.UserID,
		&i.DroppedAt,
		&i.CreatedAt,
	)
	return i, err
}

const setRoundSeed = `-- name: SetRoundSeed :one
update rounds set seed = $1, updated_at = now()
where id = $2
returning id, tournament_id, number, status, seed, published_at, completed_at, created_at, updated_at
`

type SetRoundSeedParams struct {
	Seed int64
	ID   uuid.UUID
}

func (q *Queries) SetRoundSeed(ctx context.Context, arg SetRoundSeedParams) (Round, error) {
	row := q.db.QueryRow(ctx, setRoundSeed, arg.Seed, arg.ID)
	var i Round
	err := row.Scan(
		&i.ID,
		&i.TournamentID,
		&i.Number,
		&i.Status,
		&i.Seed,
		&i.PublishedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setRoundStatus = `-- name: SetRoundStatus :one
update rounds set status = $1,
    published_at = coalesce(rounds.published_at, $2),
    completed_at = coalesce(rounds.completed_at, $3),
    updated_at = now()
where id = $4
returning id, tournament_id, number, status, seed, published_at, completed_at, created_at, updated_at
`

type SetRoundStatusParams struct {
	Status      string
	PublishedAt *time.Time
	CompletedAt *time.Time
	ID          uuid.UUID
}

func (q *Queries) SetRoundStatus(ctx context.Context, arg SetRoundStatusParams) (Round, error) {
	row := q.db.QueryRow(
		ctx, setRoundStatus,
		arg.Status,
		arg.PublishedAt,
		arg.CompletedAt,
		arg.ID,
	)
	var i Round
	err := row.Scan(
		&i.ID,
		&i.TournamentID,
		&i.Number,
		&i.Status,
		&i.Seed,
		&i.PublishedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateMatchResult = `-- name: UpdateMatchResult :one
update matches set p1_games = $1,
    p2_games = $2, draws = $3,
    reported_by = $4, reported_at = now(),
    updated_at = now()
where id = $5
returning id, round_id, table_number, player1_id, player2_id, p1_games, p2_games, draws, reported_by, reported_at, created_at, updated_at
`

type UpdateMatchResultParams struct {
	P1Games    *int32
	P2Games    *int32
	Draws      *int32
	ReportedBy pgtype.UUID
	ID         uuid.UUID
}

func (q *Queries) UpdateMatchResult(ctx context.Context, arg UpdateMatchResultParams) (Match, error) {
	row := q.db.QueryRow(
		ctx, updateMatchResult,
		arg.P1Games,
		arg.P2Games,
		arg.Draws,
		arg.ReportedBy,
		arg.ID,
	)
	var i Match
	err := row.Scan(
		&i.ID,
		&i.RoundID,
		&i.TableNumber,
		&i.Player1ID,
		&i.Player2ID,
		&i.P1Games,
		&i.P2Games,
		&i.Draws,
		&i.ReportedBy,
		&i.ReportedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePlannedRounds = `-- name: UpdatePlannedRounds :one
update tournaments set planned_rounds = $1,
    updated_at = now()
where id = $2
returning id, event_id, planned_rounds, created_at, updated_at
`

type UpdatePlannedRoundsParams struct {
	PlannedRounds int32
	ID            uuid.UUID
}

func (q *Queries) UpdatePlannedRounds(ctx context.Context, arg UpdatePlannedRoundsParams) (Tournament, error) {
	row := q.db.QueryRow(ctx, updatePlannedRounds, arg.PlannedRounds, arg.ID)
	var i Tournament
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.PlannedRounds,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
